spring:
  application:
    name: reporting-hydration-service

  featureFlag:
    elastic-search-enable: ${FF_ES_ENABLE:false}
    phc-datamart-disable: ${FF_PHC_DM_DISABLE:false}
    thread-pool-size: ${FF_THREAD_POOL_SIZE:1}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}
    group-id: ${KAFKA_CONSUMER_APP:hydration-consumer-app}
    producer:
      value-serializer: org.springframework.kafka.support.serializer.StringOrBytesSerializer
      key-serializer: org.springframework.kafka.support.serializer.StringOrBytesSerializer
    input:
      # Investigation
      topic-name-phc: nbs_Public_health_case
      topic-name-ntf: nbs_Notification
      topic-name-int: nbs_Interview
      topic-name-ctr: nbs_CT_contact
      topic-name-vac: nbs_Intervention
      topic-name-tmt: nbs_Treatment
      topic-name-ar: nbs_Act_relationship

      # Person
      topic-name: ${INPUT_TOPIC_PERSON:nbs_Person}
      topic-name-user: ${INPUT_TOPIC_USER:nbs_Auth_user}
    output:
      # Investigation
      topic-name-reporting: nrt_investigation
      topic-name-confirmation: nrt_investigation_confirmation
      topic-name-observation: nrt_investigation_observation
      topic-name-notifications: nrt_investigation_notification
      topic-name-page-case-answer: nrt_page_case_answer
      topic-name-aggregate: nrt_investigation_aggregate
      topic-name-case-management: nrt_investigation_case_management
      topic-name-interview: nrt_interview
      topic-name-interview-answer: nrt_interview_answer
      topic-name-interview-note: nrt_interview_note
      topic-name-rdb-metadata-columns: nrt_metadata_columns
      topic-name-contact: nrt_contact
      topic-name-contact-answer: nrt_contact_answer
      topic-name-vaccination: nrt_vaccination
      topic-name-vaccination-answer: nrt_vaccination_answer
      topic-name-treatment: nrt_treatment

      # Person
      providerElastic:
        topic-name: ${PROVIDER_ELASTIC:elastic_search_provider}
      providerReporting:
        topic-name: ${PROVIDER_REPORTING:nrt_provider}
      patientElastic:
        topic-name: ${PATIENT_ELASTIC:elastic_search_patient}
      patientReporting:
        topic-name: ${PATIENT_REPORTING:nrt_patient}
      userReporting:
        topic-name: ${USER_REPORTING:nrt_auth_user}
    dlq:
      retry-suffix: _retry
      dlq-suffix: _dlt
    consumer:
      max-retry: 3
      maxPollIntervalMs: 30000
      maxPollRecs: ${KAFKA_CONSUMER_MAX_POLL_RECS:200}
      key-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    admin:
      auto-create: true
    liquibase:
      change-log: db/changelog/db.changelog-master.yaml

  datasource:
    password: ${DB_PASSWORD}
    username: ${DB_USERNAME}
    url: ${DB_HOST}

management:
  endpoint:
    prometheus:
      access: read_only
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  prometheus:
    metrics:
      export:
        enabled: true

server:
  port: "8095"