CREATE  view dbo.v_nrt_nbs_page as
SELECT  distinct page.FORM_CD, page.DATAMART_NM 
--	into rdb.dbo.tmp_INIT
	FROM NBS_ODSE..PAGE_COND_MAPPING pcm 
	   INNER JOIN NBS_ODSE..NBS_PAGE page	ON pcm.WA_TEMPLATE_UID = page.WA_TEMPLATE_UID
    WHERE DATAMART_NM IS NOT NULL 
	  AND CONDITION_CD IS NOT NULL;