services:
  nbs-mssql:
    image: ghcr.io/cdcent/nedssdb:latest
    platform: linux/amd64
    environment:
      - DATABASE_VERSION=6.0.18.1
      - DEPLOY_ADMIN_PASSWORD=${DATABASE_PASSWORD:-PizzaIsGood33!}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-PizzaIsGood33!}
      - RTR_SERVICE_USER_NAME=${RTR_SERVICE_USER_NAME:-rtr_service_user}
      - RTR_SERVICE_USER_PASSWORD=${RTR_SERVICE_USER_PASSWORD:-rtr_service_user}
      - RTR_ADMIN_NAME=${RTR_ADMIN_NAME:-rtr_admin}
      - RTR_ADMIN_PASSWORD=${RTR_ADMIN_PASSWORD:-rtr_admin}
    volumes:
      - ./containers/db/initialize:/docker-entrypoint-initdb.d/
    ports:
      - 3433:1433
    mem_limit: 2.5G

  liquibase:
    build:
      dockerfile: ./liquibase-service/Dockerfile.local
    environment:
      - DB_USERNAME=${RTR_ADMIN_NAME:-rtr_admin}
      - DB_PASSWORD=${RTR_ADMIN_PASSWORD:-rtr_admin}
      - DB_HOST=nbs-mssql
      - RTR_SERVICE_USER_NAME=${RTR_SERVICE_USER_NAME:-rtr_service_user}
      - RTR_SERVICE_USER_PASSWORD=${RTR_SERVICE_USER_PASSWORD:-rtr_service_user}
    depends_on:
      nbs-mssql:
        condition: service_healthy
    mem_limit: 200M

  wildfly:
    image: ghcr.io/cdcent/nedssdev:6.0.18.1
    depends_on:
      nbs-mssql:
        condition: service_healthy
    ports:
      - "9991:9990"
      - "7003:7001"
      - "8788:8787"

  kafka:
    image: confluentinc/cp-kafka:7.8.7
    ports:
      - "9092:9092"
    environment:
      # KRaft Configuration
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      CLUSTER_ID: RwB4L8JMReqMdSiPoP-9Og # generated with docker run --rm confluentinc/cp-kafka:7.3.0 kafka-storage random-uuid

      # Listener Configuration
      KAFKA_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://kafka:9092,CONTROLLER://kafka:29093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      # Topic Configuration
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

    healthcheck:
      test: kafka-topics --bootstrap-server kafka:29092 --list
      start_period: 10s

  kafka-connect:
    build:
      dockerfile: ./containers/kafka-connect/Dockerfile
    depends_on:
      kafka:
        condition: service_healthy
      nbs-mssql:
        condition: service_healthy
      liquibase:
        condition: service_completed_successfully
    ports:
      - 8083:8083
    volumes:
      - ./containers/kafka-connect/initialize/:/kafka/healthcheck/
    environment:
      CONNECT_BOOTSTRAP_SERVERS: "kafka:29092"
      CONNECT_GROUP_ID: "cp-kafka-connect.groupId"
      CONNECT_CONFIG_STORAGE_TOPIC: "kafka-sink-connector-config"
      CONNECT_OFFSET_STORAGE_TOPIC: "kafka-sink-connector-offset"
      CONNECT_STATUS_STORAGE_TOPIC: "kafka-sink-connector-status"
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_REST_ADVERTISED_HOST_NAME: "kafka-connect"
      CONNECT_CONSUMER_METADATA_MAX_AGE_MS: 1000
      CONNECT_CONFIG_PROVIDERS: "env"
      CONNECT_CONFIG_PROVIDERS_ENV_CLASS: "org.apache.kafka.common.config.provider.EnvVarConfigProvider"
      DB_URL: "jdbc:sqlserver://nbs-mssql:1433;databaseName=rdb_modern;encrypt=true;trustServerCertificate=true;"
      DB_USERNAME: ${RTR_ADMIN_NAME:-rtr_admin}
      DB_PASSWORD: ${RTR_ADMIN_PASSWORD:-rtr_admin}
    healthcheck:
      test: ["CMD", "/kafka/healthcheck/healthcheck.sh"]
      start_period: 10s

  debezium:
    image: debezium/connect:2.4
    depends_on:
      kafka:
        condition: service_healthy
      nbs-mssql:
        condition: service_healthy
      liquibase:
        condition: service_completed_successfully
    ports:
      - "8085:8083"
    volumes:
      - ./containers/debezium/initialize/:/kafka/healthcheck/
    environment:
      BOOTSTRAP_SERVERS: kafka:29092
      GROUP_ID: connect-cluster
      KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      OFFSET_STORAGE_FILE_FILENAME: /tmp/connect.offsets
      OFFSET_FLUSH_INTERVAL_MS: 10000
      PLUGIN_PATH: /kafka/connect
      CONFIG_STORAGE_TOPIC: connect-configs
      OFFSET_STORAGE_TOPIC: connect-offsets
      STATUS_STORAGE_TOPIC: connect-status
      CONFIG_STORAGE_REPLICATION_FACTOR: 1
      OFFSET_STORAGE_REPLICATION_FACTOR: 1
      STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_CONFIG_PROVIDERS: "env"
      CONNECT_CONFIG_PROVIDERS_ENV_CLASS: "org.apache.kafka.common.config.provider.EnvVarConfigProvider"
      DB_HOST: "nbs-mssql"
      DB_PORT: "1433"
      DB_USERNAME: ${RTR_ADMIN_NAME:-rtr_admin}
      DB_PASSWORD: ${RTR_ADMIN_PASSWORD:-rtr_admin}
      KAFKA_SERVER: "kafka:29092"
    healthcheck:
      test: ["CMD", "/kafka/healthcheck/healthcheck.sh"]
      start_period: 10s

  reporting-pipeline-service:
    build:
      dockerfile: ./reporting-pipeline-service/Dockerfile
    environment:
      - DB_USERNAME=${RTR_SERVICE_USER_NAME:-rtr_service_user}
      - DB_PASSWORD=${RTR_SERVICE_USER_PASSWORD:-rtr_service_user}
      - DB_HOST=jdbc:sqlserver://nbs-mssql:1433;databaseName=RDB_MODERN;encrypt=true;trustServerCertificate=true;
      - KAFKA_BOOTSTRAP_SERVER=kafka:29092
    ports:
      - "8095:8095"
    depends_on:
      kafka:
        condition: service_healthy
      nbs-mssql:
        condition: service_healthy
      liquibase:
        condition: service_completed_successfully
      debezium:
        condition: service_healthy
      kafka-connect:
        condition: service_healthy
