--CNDE-2345
IF NOT EXISTS (SELECT 1
               FROM sysobjects
               WHERE name = 'D_ADDL_RISK_GROUP'
                 and xtype = 'U')

BEGIN				 
	CREATE TABLE DBO.D_ADDL_RISK_GROUP (
		D_ADDL_RISK_GROUP_KEY BIGINT NOT NULL ,
		PRIMARY KEY 
		(
			D_ADDL_RISK_GROUP_KEY
		) 
	);
END;

IF NOT EXISTS ( SELECT 1 FROM DBO.D_ADDL_RISK_GROUP WHERE D_ADDL_RISK_GROUP_KEY = 1 )
BEGIN
	INSERT INTO DBO.D_ADDL_RISK_GROUP (D_ADDL_RISK_GROUP_KEY) VALUES (1);
END;
