-- Fixes Error 8657 (memory grant exceeds resource pool limit) in
-- sp_std_hiv_datamart_postprocessing's "Update STD_HIV_DATAMART" / "Insert into
-- STD_HIV_DATAMART" steps. Both statements LEFT JOIN ~14 dimension tables to
-- F_STD_PAGE_CASE on what is, by design, a 1:1 key (each case has at most one row per
-- dimension). None of these join columns carried a unique index, so the optimizer
-- couldn't rule out fan-out and compounded a default multiplier across the join chain,
-- producing a cardinality estimate that peaked at ~94M rows and drove a ~889MB memory
-- grant for what is actually a tiny result set. Confirmed via STATISTICS XML: adding
-- these indexes drops that statement's cost from 100,041 to 0.458 and its granted
-- memory from ~889MB to ~2.25MB, for the same input. Verified zero duplicate key values
-- exist in each table before adding its unique constraint.

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.D_INV_ADMINISTRATIVE') AND name = N'UX_D_INV_ADMINISTRATIVE_KEY')
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX UX_D_INV_ADMINISTRATIVE_KEY ON dbo.D_INV_ADMINISTRATIVE (D_INV_ADMINISTRATIVE_KEY);
END;

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.D_INV_CLINICAL') AND name = N'UX_D_INV_CLINICAL_KEY')
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX UX_D_INV_CLINICAL_KEY ON dbo.D_INV_CLINICAL (D_INV_CLINICAL_KEY);
END;

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.D_INV_COMPLICATION') AND name = N'UX_D_INV_COMPLICATION_KEY')
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX UX_D_INV_COMPLICATION_KEY ON dbo.D_INV_COMPLICATION (D_INV_COMPLICATION_KEY);
END;

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.D_INV_CONTACT') AND name = N'UX_D_INV_CONTACT_KEY')
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX UX_D_INV_CONTACT_KEY ON dbo.D_INV_CONTACT (D_INV_CONTACT_KEY);
END;

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.D_INV_EPIDEMIOLOGY') AND name = N'UX_D_INV_EPIDEMIOLOGY_KEY')
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX UX_D_INV_EPIDEMIOLOGY_KEY ON dbo.D_INV_EPIDEMIOLOGY (D_INV_EPIDEMIOLOGY_KEY);
END;

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.D_INV_LAB_FINDING') AND name = N'UX_D_INV_LAB_FINDING_KEY')
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX UX_D_INV_LAB_FINDING_KEY ON dbo.D_INV_LAB_FINDING (D_INV_LAB_FINDING_KEY);
END;

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.D_INV_MEDICAL_HISTORY') AND name = N'UX_D_INV_MEDICAL_HISTORY_KEY')
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX UX_D_INV_MEDICAL_HISTORY_KEY ON dbo.D_INV_MEDICAL_HISTORY (D_INV_MEDICAL_HISTORY_KEY);
END;

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.D_INV_PATIENT_OBS') AND name = N'UX_D_INV_PATIENT_OBS_KEY')
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX UX_D_INV_PATIENT_OBS_KEY ON dbo.D_INV_PATIENT_OBS (D_INV_PATIENT_OBS_KEY);
END;

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.D_INV_PREGNANCY_BIRTH') AND name = N'UX_D_INV_PREGNANCY_BIRTH_KEY')
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX UX_D_INV_PREGNANCY_BIRTH_KEY ON dbo.D_INV_PREGNANCY_BIRTH (D_INV_PREGNANCY_BIRTH_KEY);
END;

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.D_INV_RISK_FACTOR') AND name = N'UX_D_INV_RISK_FACTOR_KEY')
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX UX_D_INV_RISK_FACTOR_KEY ON dbo.D_INV_RISK_FACTOR (D_INV_RISK_FACTOR_KEY);
END;

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.D_INV_SOCIAL_HISTORY') AND name = N'UX_D_INV_SOCIAL_HISTORY_KEY')
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX UX_D_INV_SOCIAL_HISTORY_KEY ON dbo.D_INV_SOCIAL_HISTORY (D_INV_SOCIAL_HISTORY_KEY);
END;

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.D_INV_SYMPTOM') AND name = N'UX_D_INV_SYMPTOM_KEY')
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX UX_D_INV_SYMPTOM_KEY ON dbo.D_INV_SYMPTOM (D_INV_SYMPTOM_KEY);
END;

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.D_INV_TREATMENT') AND name = N'UX_D_INV_TREATMENT_KEY')
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX UX_D_INV_TREATMENT_KEY ON dbo.D_INV_TREATMENT (D_INV_TREATMENT_KEY);
END;

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.D_CASE_MANAGEMENT') AND name = N'UX_D_CASE_MANAGEMENT_KEY')
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX UX_D_CASE_MANAGEMENT_KEY ON dbo.D_CASE_MANAGEMENT (D_CASE_MANAGEMENT_KEY);
END;

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'dbo.INV_HIV') AND name = N'UX_INV_HIV_INVESTIGATION_KEY')
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX UX_INV_HIV_INVESTIGATION_KEY ON dbo.INV_HIV (INVESTIGATION_KEY);
END;
