FROM liquibase/liquibase:5.0.2-alpine

USER root

# TARGETARCH is automatically set (amd64, arm64, etc.)
ARG TARGETARCH

RUN if [ "$TARGETARCH" = "amd64" ]; then \
        apk add --no-cache wget && \
        wget https://download.microsoft.com/download/fae28b9a-d880-42fd-9b98-d779f0fdd77f/msodbcsql18_18.5.1.1-1_amd64.apk --no-check-certificate && \
        wget https://download.microsoft.com/download/7/6/d/76de322a-d860-4894-9945-f0cc5d6a45f8/mssql-tools18_18.4.1.1-1_amd64.apk --no-check-certificate && \
        apk add --allow-untrusted msodbcsql18_18.5.1.1-1_amd64.apk && \
        apk add --allow-untrusted mssql-tools18_18.4.1.1-1_amd64.apk; \
    elif [ "$TARGETARCH" = "arm64" ]; then \
        apk add --no-cache wget && \
        wget https://download.microsoft.com/download/fae28b9a-d880-42fd-9b98-d779f0fdd77f/msodbcsql18_18.5.1.1-1_arm64.apk --no-check-certificate && \
        wget https://download.microsoft.com/download/7/6/d/76de322a-d860-4894-9945-f0cc5d6a45f8/mssql-tools18_18.4.1.1-1_arm64.apk --no-check-certificate && \
        apk add --allow-untrusted msodbcsql18_18.5.1.1-1_arm64.apk && \
        apk add --allow-untrusted mssql-tools18_18.4.1.1-1_arm64.apk; \
    fi

# Install Microsoft SQL Server JDBC driver for Liquibase
ARG MSSQL_JDBC_VERSION=13.4.0
ARG MSSQL_JDBC_SHA256=e36f5237c1267983e5b88dc2169f6b9d7e50eceec6dc1ca31018e3877e14af66

RUN apk add --no-cache wget coreutils && \
    wget -O /liquibase/lib/mssql-jdbc-${MSSQL_JDBC_VERSION}.jre11.jar \
      https://github.com/microsoft/mssql-jdbc/releases/download/v${MSSQL_JDBC_VERSION}/mssql-jdbc-${MSSQL_JDBC_VERSION}.jre11.jar && \
    echo "${MSSQL_JDBC_SHA256}  /liquibase/lib/mssql-jdbc-${MSSQL_JDBC_VERSION}.jre11.jar" | sha256sum -c -

#Copy sources
#changelog
COPY liquibase-service/src/main/resources/db/changelog /liquibase/changelog
#master
COPY liquibase-service/src/main/resources/db/001-master /liquibase/changelog
COPY liquibase-service/src/main/resources/db/001-master/functions /liquibase/changelog
#srte
COPY liquibase-service/src/main/resources/db/002-srte /liquibase/changelog
COPY liquibase-service/src/main/resources/db/002-srte/tables /liquibase/changelog
#odse
COPY liquibase-service/src/main/resources/db/003-odse /liquibase/changelog
COPY liquibase-service/src/main/resources/db/003-odse/views /liquibase/changelog
#rdb
COPY liquibase-service/src/main/resources/db/004-rdb /liquibase/changelog
COPY liquibase-service/src/main/resources/db/004-rdb/tables /liquibase/changelog
#rdb_modern
COPY liquibase-service/src/main/resources/db/005-rdb_modern /liquibase/changelog
COPY liquibase-service/src/main/resources/db/005-rdb_modern/routines /liquibase/changelog
COPY liquibase-service/src/main/resources/db/005-rdb_modern/functions /liquibase/changelog
COPY liquibase-service/src/main/resources/db/005-rdb_modern/tables /liquibase/changelog
COPY liquibase-service/src/main/resources/db/005-rdb_modern/views /liquibase/changelog
# Onboarding
COPY liquibase-service/src/main/resources/db/001-master/01_onboarding_scripts_user_creation/ /liquibase/changelog/onboarding/
COPY liquibase-service/src/main/resources/db/001-master/02_onboarding_script_data_load/ /liquibase/changelog/onboarding/

#Set the Working Directory
WORKDIR /liquibase/changelog
USER liquibase

COPY --chown=liquibase ../containers/liquibase/migrate.sh .

CMD ["./migrate.sh"]
