/* APP-926 perf repro seed — small & fast (reproduces the EVENT_METRIC scan on line 77).
   Scale: EVENT_METRIC 5,000,000 (unindexed on EVENT_UID => scan); MORBIDITY_REPORT/EVENT 50,000.
   Reports qualify via @obs_uids (CAST(MORB_RPT_UID AS bigint)), so dimension tables stay empty.
   Batched with CHECKPOINT so SIMPLE-recovery log stays tiny (RDB_log was capped at 100MB). */
USE RDB_MODERN;
SET NOCOUNT ON;

ALTER DATABASE RDB_MODERN SET RECOVERY SIMPLE;
ALTER DATABASE RDB_MODERN MODIFY FILE (NAME = RDB_log, MAXSIZE = UNLIMITED);

TRUNCATE TABLE dbo.EVENT_METRIC;
DELETE FROM dbo.MORBIDITY_REPORT WHERE MORB_RPT_KEY <> 1;
TRUNCATE TABLE dbo.MORBIDITY_REPORT_EVENT;

/* ---- EVENT_METRIC: 5,000,000 rows in 50 batches of 100k, checkpoint each ---- */
DECLARE @b INT = 0;
WHILE @b < 50
BEGIN
    ;WITH n AS (
        SELECT TOP (100000) ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS rn
        FROM sys.all_columns a CROSS JOIN sys.all_columns b
    )
    INSERT INTO dbo.EVENT_METRIC
        (EVENT_TYPE, EVENT_UID, PROG_AREA_DESC_TXT, ADD_TIME, ADD_USER_ID, LAST_CHG_TIME, LAST_CHG_USER_ID, ADD_USER_NAME, LAST_CHG_USER_NAME)
    SELECT 'Observation', CAST(@b*100000 + rn AS bigint), 'Enteric', GETDATE(), 1, GETDATE(), 1, 'seed_add_user', 'seed_chg_user'
    FROM n;
    CHECKPOINT;
    SET @b += 1;
END

/* ---- MORBIDITY_REPORT: 50k rows, keys 2..50001, MORB_RPT_UID overlaps EVENT_UID range ---- */
;WITH n AS (SELECT TOP (50000) ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS rn FROM sys.all_columns a CROSS JOIN sys.all_columns b)
INSERT INTO dbo.MORBIDITY_REPORT (MORB_RPT_KEY, MORB_RPT_UID, RECORD_STATUS_CD)
SELECT CAST(rn+1 AS bigint), CAST(rn+1 AS bigint), 'ACTIVE' FROM n;
CHECKPOINT;

/* ---- MORBIDITY_REPORT_EVENT: 1 per report; NOT-NULL key cols = 1 (dims empty => LEFT JOIN misses) ---- */
;WITH n AS (SELECT TOP (50000) ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS rn FROM sys.all_columns a CROSS JOIN sys.all_columns b)
INSERT INTO dbo.MORBIDITY_REPORT_EVENT
    (MORB_RPT_KEY, PATIENT_KEY, PHYSICIAN_KEY, REPORTER_KEY, MORB_RPT_SRC_ORG_KEY, HSPTL_KEY, INVESTIGATION_KEY, CONDITION_KEY,
     NURSING_HOME_KEY, HEALTH_CARE_KEY, LDF_GROUP_KEY, MORB_RPT_CREATE_DT_KEY, HSPTL_DISCHARGE_DT_KEY, ILLNESS_ONSET_DT_KEY, MORB_RPT_DT_KEY, RECORD_STATUS_CD)
SELECT CAST(rn+1 AS bigint), 1,1,1,1,1,1,1, 1,1,1,1,1,1,1, 'ACTIVE' FROM n;
CHECKPOINT;

SELECT 'EVENT_METRIC='+CAST(COUNT_BIG(*) AS VARCHAR) FROM dbo.EVENT_METRIC;
SELECT 'MORBIDITY_REPORT='+CAST(COUNT_BIG(*) AS VARCHAR) FROM dbo.MORBIDITY_REPORT;
SELECT 'MORBIDITY_REPORT_EVENT='+CAST(COUNT_BIG(*) AS VARCHAR) FROM dbo.MORBIDITY_REPORT_EVENT;
