/*  APP-926 equivalence-test seed.
    Idempotent. Enriches dims + repoints a handful of MORBIDITY_REPORT_EVENT
    FK keys so the pat / prov / org / inv branches can actually match.
    Obs-path data (MORB_RPT_UID = MORB_RPT_KEY, keys 2..50001) left intact.

    Known UIDs chosen to avoid the obs range (2..50001) and the junk tokens
    (0, -1, 999999999999):
      pat  UID 8000001  key 8000001  -> MRE MORB_RPT_KEY 2 (PATIENT_KEY)
      prov UID 8000002  key 8000002  -> MRE MORB_RPT_KEY 3 (PHYSICIAN_KEY)
      prov UID 8000003  key 8000003  -> MRE MORB_RPT_KEY 4 (REPORTER_KEY)
      org  UID 8000004  key 8000004  -> MRE MORB_RPT_KEY 5 (MORB_RPT_SRC_ORG_KEY)
      org  UID 8000005  key 8000005  -> MRE MORB_RPT_KEY 6 (HSPTL_KEY)
      inv  CASE_UID 10000013 key 2   -> MRE MORB_RPT_KEY 7 (INVESTIGATION_KEY)  [pre-existing row]

    MULTI-EVENT case (scenario 9): report MORB_RPT_KEY 30 has TWO MRE rows.
      - pre-existing MRE row (PATIENT_KEY=1, all FK keys=1) -> matches NOTHING (dims empty / UID NULL).
      - added MRE row (PATIENT_KEY=8000010) -> matches the pat branch (D_PATIENT 8000010, UID 8000010).
    The ORIGINAL SP's WHERE decides per (MR,MRE) row, so only the matching MRE emits a datamart row.
    This is the case a naive key-grain rewrite would break (it would emit the non-matching MRE's data
    or emit both). Proves the #cand rewrite still keeps the row-grain WHERE.
    pat UID 8000010 is dedicated to scenario 9 (distinct from scenario-2's 8000001) so scenarios stay independent.
*/
SET NOCOUNT ON;

IF NOT EXISTS (SELECT 1 FROM dbo.D_PATIENT WHERE PATIENT_KEY = 8000001)
    INSERT INTO dbo.D_PATIENT (PATIENT_KEY, PATIENT_UID) VALUES (8000001, 8000001);

IF NOT EXISTS (SELECT 1 FROM dbo.D_PROVIDER WHERE PROVIDER_KEY = 8000002)
    INSERT INTO dbo.D_PROVIDER (PROVIDER_KEY, PROVIDER_UID) VALUES (8000002, 8000002);
IF NOT EXISTS (SELECT 1 FROM dbo.D_PROVIDER WHERE PROVIDER_KEY = 8000003)
    INSERT INTO dbo.D_PROVIDER (PROVIDER_KEY, PROVIDER_UID) VALUES (8000003, 8000003);

IF NOT EXISTS (SELECT 1 FROM dbo.D_ORGANIZATION WHERE ORGANIZATION_KEY = 8000004)
    INSERT INTO dbo.D_ORGANIZATION (ORGANIZATION_KEY, ORGANIZATION_UID) VALUES (8000004, 8000004);
IF NOT EXISTS (SELECT 1 FROM dbo.D_ORGANIZATION WHERE ORGANIZATION_KEY = 8000005)
    INSERT INTO dbo.D_ORGANIZATION (ORGANIZATION_KEY, ORGANIZATION_UID) VALUES (8000005, 8000005);

-- INVESTIGATION key=2 (CASE_UID 10000013) already exists; ensure it's ACTIVE.
UPDATE dbo.INVESTIGATION SET RECORD_STATUS_CD = 'ACTIVE' WHERE INVESTIGATION_KEY = 2;

UPDATE dbo.MORBIDITY_REPORT_EVENT SET PATIENT_KEY          = 8000001 WHERE MORB_RPT_KEY = 2;
UPDATE dbo.MORBIDITY_REPORT_EVENT SET PHYSICIAN_KEY        = 8000002 WHERE MORB_RPT_KEY = 3;
UPDATE dbo.MORBIDITY_REPORT_EVENT SET REPORTER_KEY         = 8000003 WHERE MORB_RPT_KEY = 4;
UPDATE dbo.MORBIDITY_REPORT_EVENT SET MORB_RPT_SRC_ORG_KEY = 8000004 WHERE MORB_RPT_KEY = 5;
UPDATE dbo.MORBIDITY_REPORT_EVENT SET HSPTL_KEY            = 8000005 WHERE MORB_RPT_KEY = 6;
UPDATE dbo.MORBIDITY_REPORT_EVENT SET INVESTIGATION_KEY    = 2       WHERE MORB_RPT_KEY = 7;

-- MULTI-EVENT scenario (9): dedicated patient dim + a SECOND MRE row for report 30.
IF NOT EXISTS (SELECT 1 FROM dbo.D_PATIENT WHERE PATIENT_KEY = 8000010)
    INSERT INTO dbo.D_PATIENT (PATIENT_KEY, PATIENT_UID) VALUES (8000010, 8000010);

-- report 30 keeps its original non-matching MRE row (PATIENT_KEY=1); add one matching MRE row.
IF NOT EXISTS (SELECT 1 FROM dbo.MORBIDITY_REPORT_EVENT WHERE MORB_RPT_KEY = 30 AND PATIENT_KEY = 8000010)
    INSERT INTO dbo.MORBIDITY_REPORT_EVENT
        (MORB_RPT_KEY, PATIENT_KEY, PHYSICIAN_KEY, REPORTER_KEY, MORB_RPT_SRC_ORG_KEY, HSPTL_KEY, INVESTIGATION_KEY, CONDITION_KEY,
         NURSING_HOME_KEY, HEALTH_CARE_KEY, LDF_GROUP_KEY, MORB_RPT_CREATE_DT_KEY, HSPTL_DISCHARGE_DT_KEY, ILLNESS_ONSET_DT_KEY, MORB_RPT_DT_KEY, RECORD_STATUS_CD)
    VALUES (30, 8000010, 1, 1, 1, 1, 1, 1,  1, 1, 1, 1, 1, 1, 1, 'ACTIVE');

SELECT 'seed done' AS status;
SELECT 'multi-event report 30 MRE rows' AS note, MORB_RPT_KEY, PATIENT_KEY
FROM dbo.MORBIDITY_REPORT_EVENT WHERE MORB_RPT_KEY = 30 ORDER BY PATIENT_KEY;
SELECT MORB_RPT_KEY, PATIENT_KEY, PHYSICIAN_KEY, REPORTER_KEY, MORB_RPT_SRC_ORG_KEY, HSPTL_KEY, INVESTIGATION_KEY
FROM dbo.MORBIDITY_REPORT_EVENT WHERE MORB_RPT_KEY IN (2,3,4,5,6,7) ORDER BY MORB_RPT_KEY;
