USE [NBS_MSGOUTE];
GO

INSERT INTO [dbo].[NBS_interface]
(
    payload,
    imp_exp_ind_cd,
    record_status_cd,
    record_status_time,
    add_time,
    system_nm,
    doc_type_cd,
    filler_order_nbr,
    lab_clia,
    order_test_code,
    specimen_coll_date
)
VALUES (
    '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Container xmlns="http://www.cdc.gov/NEDSS">
    <HL7LabReport>
        <HL7MSH>
            <FieldSeparator>|</FieldSeparator>
            <EncodingCharacters>^~\&amp;</EncodingCharacters>
            <SendingApplication>
                <HL7NamespaceID>TEST_ELR_APP</HL7NamespaceID>
                <HL7UniversalID>2.16.840.1.113883.19.3.2.1</HL7UniversalID>
                <HL7UniversalIDType>ISO</HL7UniversalIDType>
            </SendingApplication>
            <SendingFacility>
                <HL7NamespaceID>CDC TEST LAB</HL7NamespaceID>
                <HL7UniversalID>99D9999999</HL7UniversalID>
                <HL7UniversalIDType>CLIA</HL7UniversalIDType>
            </SendingFacility>
            <ReceivingApplication>
                <HL7NamespaceID>NBS</HL7NamespaceID>
                <HL7UniversalID>2.16.840.1.113883.19.4.1</HL7UniversalID>
                <HL7UniversalIDType>ISO</HL7UniversalIDType>
            </ReceivingApplication>
            <ReceivingFacility>
                <HL7NamespaceID>PUBLIC HEALTH</HL7NamespaceID>
                <HL7UniversalID>2.16.840.1.113883.19.4.2</HL7UniversalID>
                <HL7UniversalIDType>ISO</HL7UniversalIDType>
            </ReceivingFacility>
            <DateTimeOfMessage>
                <year>2026</year>
                <month>05</month>
                <day>01</day>
                <hours>14</hours>
                <minutes>30</minutes>
                <seconds>00</seconds>
                <gmtOffset>-0500</gmtOffset>
            </DateTimeOfMessage>
            <Security/>
            <MessageType>
                <MessageCode>ORU</MessageCode>
                <TriggerEvent>R01</TriggerEvent>
                <MessageStructure>ORU_R01</MessageStructure>
            </MessageType>
            <MessageControlID>ELR-STD-0001</MessageControlID>
            <ProcessingID>
                <HL7ProcessingID>T</HL7ProcessingID>
                <HL7ProcessingMode/>
            </ProcessingID>
            <VersionID>
                <HL7VersionID>2.5.1</HL7VersionID>
            </VersionID>
            <AcceptAcknowledgmentType>AL</AcceptAcknowledgmentType>
            <ApplicationAcknowledgmentType>NE</ApplicationAcknowledgmentType>
            <CountryCode>USA</CountryCode>
            <CharacterSet/>
            <MessageProfileIdentifier>
                <HL7EntityIdentifier>PHLabReport-Ack</HL7EntityIdentifier>
                <HL7NamespaceID/>
                <HL7UniversalID>2.16.840.1.113883.9.10</HL7UniversalID>
                <HL7UniversalIDType>ISO</HL7UniversalIDType>
            </MessageProfileIdentifier>
        </HL7MSH>
        <HL7PATIENT_RESULT>
            <PATIENT>
                <PatientIdentification>
                    <SetIDPID>
                        <HL7SequenceID>1</HL7SequenceID>
                    </SetIDPID>
                    <PatientIdentifierList>
                        <HL7IDNumber>ARTHUR-JONES-STD-001</HL7IDNumber>
                        <HL7AssigningAuthority>
                            <HL7NamespaceID>TEST_ELR_APP</HL7NamespaceID>
                            <HL7UniversalID>2.16.840.1.113883.19.3.2.1</HL7UniversalID>
                            <HL7UniversalIDType>ISO</HL7UniversalIDType>
                        </HL7AssigningAuthority>
                        <HL7IdentifierTypeCode>PI</HL7IdentifierTypeCode>
                    </PatientIdentifierList>
                    <PatientName>
                        <HL7FamilyName>
                            <HL7Surname>JONES</HL7Surname>
                        </HL7FamilyName>
                        <HL7GivenName>ARTHUR</HL7GivenName>
                        <HL7Degree/>
                    </PatientName>
                    <DateTimeOfBirth>
                        <year>1988</year>
                        <month>05</month>
                        <day>05</day>
                    </DateTimeOfBirth>
                    <AdministrativeSex>M</AdministrativeSex>
                    <Race>
                        <HL7Identifier>2106-3</HL7Identifier>
                        <HL7Text>White</HL7Text>
                        <HL7NameofCodingSystem>CDCREC</HL7NameofCodingSystem>
                    </Race>
                    <PatientAddress>
                        <HL7StreetAddress>
                            <HL7StreetOrMailingAddress>1600 Clifton Rd NE</HL7StreetOrMailingAddress>
                        </HL7StreetAddress>
                        <HL7City>Atlanta</HL7City>
                        <HL7StateOrProvince>GA</HL7StateOrProvince>
                        <HL7ZipOrPostalCode>30333</HL7ZipOrPostalCode>
                        <HL7Country>USA</HL7Country>
                        <HL7AddressType>H</HL7AddressType>
                    </PatientAddress>
                    <PhoneNumberHome>
                        <HL7TelecommunicationUseCode>PRN</HL7TelecommunicationUseCode>
                        <HL7TelecommunicationEquipmentType>PH</HL7TelecommunicationEquipmentType>
                        <HL7CountryCode>
                            <HL7Numeric>1</HL7Numeric>
                        </HL7CountryCode>
                        <HL7AreaCityCode>
                            <HL7Numeric>404</HL7Numeric>
                        </HL7AreaCityCode>
                        <HL7LocalNumber>
                            <HL7Numeric>6393311</HL7Numeric>
                        </HL7LocalNumber>
                        <HL7Extension/>
                    </PhoneNumberHome>
                    <SSNNumberPatient/>
                    <EthnicGroup>
                        <HL7Identifier>N</HL7Identifier>
                        <HL7Text>Not Hispanic or Latino</HL7Text>
                        <HL7NameofCodingSystem>HL70189</HL7NameofCodingSystem>
                    </EthnicGroup>
                    <BirthOrder/>
                </PatientIdentification>
            </PATIENT>
            <ORDER_OBSERVATION>
                <CommonOrder>
                    <OrderControl>RE</OrderControl>
                    <PlacerOrderNumber>
                        <HL7EntityIdentifier>ORD-STD-20260501-001</HL7EntityIdentifier>
                        <HL7NamespaceID>TEST_ELR_APP</HL7NamespaceID>
                        <HL7UniversalID>2.16.840.1.113883.19.3.2.1</HL7UniversalID>
                        <HL7UniversalIDType>ISO</HL7UniversalIDType>
                    </PlacerOrderNumber>
                    <FillerOrderNumber>
                        <HL7EntityIdentifier>LAB-STD-20260501-001</HL7EntityIdentifier>
                        <HL7NamespaceID>CDC TEST LAB</HL7NamespaceID>
                        <HL7UniversalID>99D9999999</HL7UniversalID>
                        <HL7UniversalIDType>CLIA</HL7UniversalIDType>
                    </FillerOrderNumber>
                    <PlacerGroupNumber>
                        <HL7EntityIdentifier>ORD-STD-20260501-001</HL7EntityIdentifier>
                        <HL7NamespaceID>TEST_ELR_APP</HL7NamespaceID>
                        <HL7UniversalID>2.16.840.1.113883.19.3.2.1</HL7UniversalID>
                        <HL7UniversalIDType>ISO</HL7UniversalIDType>
                    </PlacerGroupNumber>
                    <OrderStatus>A</OrderStatus>
                    <DateTimeOfTransaction>
                        <year>2026</year>
                        <month>05</month>
                        <day>01</day>
                        <hours>14</hours>
                        <minutes>30</minutes>
                        <seconds>00</seconds>
                        <gmtOffset>-0500</gmtOffset>
                    </DateTimeOfTransaction>
                    <OrderingProvider>
                        <HL7IDNumber>9999999999</HL7IDNumber>
                        <HL7FamilyName>
                            <HL7Surname>SAMPLE</HL7Surname>
                        </HL7FamilyName>
                        <HL7GivenName>SARAH</HL7GivenName>
                        <HL7NameTypeCode>NPI</HL7NameTypeCode>
                        <HL7IdentifierTypeCode>NPI</HL7IdentifierTypeCode>
                    </OrderingProvider>
                    <OrderingFacilityName>
                        <HL7OrganizationName>CDC TEST CLINIC</HL7OrganizationName>
                        <HL7OrganizationNameTypeCode/>
                        <HL7IDNumber/>
                        <HL7CheckDigit/>
                        <HL7AssigningAuthority/>
                        <HL7IdentifierTypeCode>L</HL7IdentifierTypeCode>
                        <HL7OrganizationIdentifier/>
                    </OrderingFacilityName>
                    <OrderingFacilityAddress>
                        <HL7StreetAddress>
                            <HL7StreetOrMailingAddress>1600 Clifton Rd NE</HL7StreetOrMailingAddress>
                        </HL7StreetAddress>
                        <HL7City>Atlanta</HL7City>
                        <HL7StateOrProvince>GA</HL7StateOrProvince>
                        <HL7ZipOrPostalCode>30333</HL7ZipOrPostalCode>
                        <HL7Country>USA</HL7Country>
                        <HL7AddressType>B</HL7AddressType>
                    </OrderingFacilityAddress>
                    <OrderingFacilityPhoneNumber>
                        <HL7TelecommunicationUseCode>WPN</HL7TelecommunicationUseCode>
                        <HL7TelecommunicationEquipmentType>PH</HL7TelecommunicationEquipmentType>
                        <HL7CountryCode>
                            <HL7Numeric>1</HL7Numeric>
                        </HL7CountryCode>
                        <HL7AreaCityCode>
                            <HL7Numeric>404</HL7Numeric>
                        </HL7AreaCityCode>
                        <HL7LocalNumber>
                            <HL7Numeric>6393311</HL7Numeric>
                        </HL7LocalNumber>
                        <HL7Extension/>
                    </OrderingFacilityPhoneNumber>
                    <OrderingProviderAddress>
                        <HL7StreetAddress>
                            <HL7StreetOrMailingAddress>1600 Clifton Rd NE</HL7StreetOrMailingAddress>
                        </HL7StreetAddress>
                        <HL7City>Atlanta</HL7City>
                        <HL7StateOrProvince>GA</HL7StateOrProvince>
                        <HL7ZipOrPostalCode>30333</HL7ZipOrPostalCode>
                        <HL7Country>USA</HL7Country>
                        <HL7AddressType>B</HL7AddressType>
                    </OrderingProviderAddress>
                </CommonOrder>
                <ObservationRequest>
                    <SetIDOBR>
                        <HL7SequenceID>1</HL7SequenceID>
                    </SetIDOBR>
                    <PlacerOrderNumber>
                        <HL7EntityIdentifier>ORD-STD-20260501-001</HL7EntityIdentifier>
                        <HL7NamespaceID>TEST_ELR_APP</HL7NamespaceID>
                        <HL7UniversalID>2.16.840.1.113883.19.3.2.1</HL7UniversalID>
                        <HL7UniversalIDType>ISO</HL7UniversalIDType>
                    </PlacerOrderNumber>
                    <FillerOrderNumber>
                        <HL7EntityIdentifier>LAB-STD-20260501-001</HL7EntityIdentifier>
                        <HL7NamespaceID>CDC TEST LAB</HL7NamespaceID>
                        <HL7UniversalID>99D9999999</HL7UniversalID>
                        <HL7UniversalIDType>CLIA</HL7UniversalIDType>
                    </FillerOrderNumber>
                    <UniversalServiceIdentifier>
                        <HL7Identifier>LP29684-5</HL7Identifier>
                        <HL7Text>Measles virus RNA [Presence] in Specimen by NAA with probe detection</HL7Text>
                        <HL7NameofCodingSystem>LN</HL7NameofCodingSystem>
                    </UniversalServiceIdentifier>
                    <ObservationDateTime>
                        <year>2026</year>
                        <month>05</month>
                        <day>01</day>
                        <hours>09</hours>
                        <minutes>30</minutes>
                        <seconds>00</seconds>
                        <gmtOffset>-0500</gmtOffset>
                    </ObservationDateTime>
                    <SpecimenReceivedDateTime>
                        <year>2026</year>
                        <month>05</month>
                        <day>01</day>
                        <hours>10</hours>
                        <minutes>15</minutes>
                        <seconds>00</seconds>
                        <gmtOffset>-0500</gmtOffset>
                    </SpecimenReceivedDateTime>
                    <OrderingProvider>
                        <HL7IDNumber>9999999999</HL7IDNumber>
                        <HL7FamilyName>
                            <HL7Surname>SAMPLE</HL7Surname>
                        </HL7FamilyName>
                        <HL7GivenName>SARAH</HL7GivenName>
                        <HL7NameTypeCode>NPI</HL7NameTypeCode>
                        <HL7IdentifierTypeCode>NPI</HL7IdentifierTypeCode>
                    </OrderingProvider>
                    <ResultsRptStatusChngDateTime>
                        <year>2026</year>
                        <month>05</month>
                        <day>01</day>
                        <hours>14</hours>
                        <minutes>30</minutes>
                        <seconds>00</seconds>
                        <gmtOffset>-0500</gmtOffset>
                    </ResultsRptStatusChngDateTime>
                    <ResultStatus>F</ResultStatus>
                    <NumberofSampleContainers/>
                </ObservationRequest>
                <PatientResultOrderObservation>
                    <OBSERVATION>
                        <ObservationResult>
                            <SetIDOBX>
                                <HL7SequenceID>1</HL7SequenceID>
                            </SetIDOBX>
                            <ValueType>CWE</ValueType>
                            <ObservationIdentifier>
                                <HL7Identifier>LP29684-5</HL7Identifier>
                                <HL7Text>Measles virus RNA [Presence] in Specimen by NAA with probe detection</HL7Text>
                                <HL7NameofCodingSystem>LN</HL7NameofCodingSystem>
                            </ObservationIdentifier>
                            <ObservationValue>260415000^Not detected^SCT^NEG^Negative^L</ObservationValue>
                            <Probability/>
                            <ObservationResultStatus>F</ObservationResultStatus>
                            <DateTimeOftheObservation>
                                <year>2026</year>
                                <month>05</month>
                                <day>01</day>
                                <hours>09</hours>
                                <minutes>30</minutes>
                                <seconds>00</seconds>
                                <gmtOffset>-0500</gmtOffset>
                            </DateTimeOftheObservation>
                            <DateTimeOftheAnalysis>
                                <year>2026</year>
                                <month>05</month>
                                <day>01</day>
                                <hours>14</hours>
                                <minutes>30</minutes>
                                <seconds>00</seconds>
                                <gmtOffset>-0500</gmtOffset>
                            </DateTimeOftheAnalysis>
                        </ObservationResult>
                    </OBSERVATION>
                </PatientResultOrderObservation>
            </ORDER_OBSERVATION>
        </HL7PATIENT_RESULT>
    </HL7LabReport>
</Container>
',
    N'I',                                   -- Import indicator
    N'QUEUED',                              -- Status: queued for processing
    CURRENT_TIMESTAMP,                      -- Record status time
    CURRENT_TIMESTAMP,                      -- Add time
    N'NBS',                                 -- System name
    N'11648804',                            -- ELR document type code
    N'LAB-STD-20260501-001',      -- filler_order_nbr from OBR.FillerOrderNumber.EntityIdentifier
    N'99D9999999',              -- lab_clia from MSH.SendingFacility.UniversalID
    N'LP29684-5',       -- order_test_code from OBR.UniversalServiceIdentifier.Identifier
    NULL                     -- specimen_coll_date from SPM.SpecimenCollectionDateTime
);

