IF EXISTS(SELECT * FROM sys.views WHERE name = 'v_nrt_d_provider_rdb_table_metadata')
BEGIN
    DROP VIEW [dbo].v_nrt_d_provider_rdb_table_metadata
END;
GO

CREATE VIEW [dbo].v_nrt_d_provider_rdb_table_metadata 
AS
SELECT DISTINCT 
	RDB_COLUMN_NM, 
	user_defined_column_nm, 
	CASE
		WHEN part_type_cd= 'CASupervisorOfPHC' THEN 'SUPRVSR_OF_CASE_ASSGNMENT_KEY'
		WHEN PART_TYPE_CD='ClosureInvestgrOfPHC' THEN 'CLOSED_BY_KEY'	   
		WHEN PART_TYPE_CD= 'DispoFldFupInvestgrOfPHC' THEN 'DISPOSITIONED_BY_KEY'	   
		WHEN PART_TYPE_CD= 'FldFupInvestgrOfPHC'  THEN'INVSTGTR_FLD_FOLLOW_UP_KEY'	  
		WHEN PART_TYPE_CD= 'FldFupProvOfPHC' THEN'PROVIDER_FLD_FOLLOW_UP_KEY'	   
		WHEN PART_TYPE_CD= 'FldFupSupervisorOfPHC' THEN'SUPRVSR_OF_FLD_FOLLOW_UP_KEY'	   
		WHEN PART_TYPE_CD= 'InitFldFupInvestgrOfPHC' THEN'INIT_ASGNED_FLD_FOLLOW_UP_KEY'	  
		WHEN PART_TYPE_CD= 'InitFupInvestgrOfPHC' THEN'INIT_FOLLOW_UP_INVSTGTR_KEY'	   
		WHEN PART_TYPE_CD= 'InitInterviewerOfPHC' THEN'INIT_ASGNED_INTERVIEWER_KEY'	  
		WHEN PART_TYPE_CD= 'InterviewerOfPHC' THEN'INTERVIEWER_ASSIGNED_KEY'	 
		WHEN PART_TYPE_CD= 'InvestgrOfPHC' THEN'INVESTIGATOR_KEY'	  
		WHEN PART_TYPE_CD= 'PerAsProviderOfDelivery' THEN'DELIVERING_MD_KEY'	  
		WHEN PART_TYPE_CD= 'PerAsProviderOfOBGYN' THEN'MOTHER_OB_GYN_KEY'	   
		WHEN PART_TYPE_CD= 'PerAsProvideroOfPediatrics' THEN'PEDIATRICIAN_KEY'	  
		WHEN PART_TYPE_CD= 'PerAsReporterOfPHC' THEN'PERSON_AS_REPORTER_KEY'	   
		WHEN PART_TYPE_CD= 'PhysicianOfPHC' THEN'PHYSICIAN_KEY'	  
		WHEN PART_TYPE_CD= 'SurvInvestgrOfPHC' THEN'SURVEILLANCE_INVESTIGATOR_KEY'	   
		WHEN PART_TYPE_CD= 'FldFupFacilityOfPHC' THEN'FACILITY_FLD_FOLLOW_UP_KEY'	   
		WHEN PART_TYPE_CD= 'HospOfADT' THEN'HOSPITAL_KEY'	   
		WHEN PART_TYPE_CD= 'OrgAsClinicOfPHC' THEN'ORDERING_FACILITY_KEY'	   
		WHEN PART_TYPE_CD= 'OrgAsHospitalOfDelivery' THEN 'DELIVERING_HOSP_KEY'	   
		WHEN PART_TYPE_CD= 'OrgAsReporterOfPHC' THEN 'ORG_AS_REPORTER_KEY'	 
	END part_type_cd,
	CAST(SUBSTRING(USER_DEFINED_COLUMN_NM,1,CHARINDEX('_UID',USER_DEFINED_COLUMN_NM))+'KEY' AS VARCHAR(2000)) AS [Key],
	CAST(SUBSTRING(USER_DEFINED_COLUMN_NM,1,CHARINDEX('_UID',USER_DEFINED_COLUMN_NM))+'DETAIL' AS VARCHAR(2000)) AS Detail,
	CAST(SUBSTRING(USER_DEFINED_COLUMN_NM,1,CHARINDEX('_UID',USER_DEFINED_COLUMN_NM))+'QEC' AS VARCHAR(2000)) AS QEC,
	CAST(USER_DEFINED_COLUMN_NM AS VARCHAR(2000)) AS [UID],
	INVESTIGATION_FORM_CD
FROM [dbo].v_nrt_odse_NBS_rdb_metadata_recent rdb_meta WITH(NOLOCK)
INNER JOIN [dbo].nrt_odse_NBS_ui_metadata ui_meta WITH(NOLOCK)
	ON rdb_meta.NBS_UI_METADATA_UID =ui_meta.NBS_UI_METADATA_UID
WHERE 
	rdb_meta.USER_DEFINED_COLUMN_NM <> '' 
	AND rdb_meta.USER_DEFINED_COLUMN_NM IS NOT NULL
	AND PART_TYPE_CD IS NOT NULL 
	AND RDB_TABLE_NM ='D_PROVIDER' 
	AND DATA_TYPE='PART';