IF NOT EXISTS (SELECT 1
               FROM sysobjects
               WHERE name = 'D_MOVE_CNTY'
                 and xtype = 'U')

BEGIN				 
	CREATE TABLE DBO.D_MOVE_CNTY (
		TB_PAM_UID BIGINT NOT NULL ,
		D_MOVE_CNTY_KEY BIGINT NOT NULL ,
		SEQ_NBR INT NULL ,
		D_MOVE_CNTY_GROUP_KEY BIGINT NOT NULL ,
		LAST_CHG_TIME DATETIME NULL ,
		VALUE VARCHAR (250) NULL ,
		CONSTRAINT PK_D_MOVE_CNTY PRIMARY KEY  CLUSTERED 
		(
			D_MOVE_CNTY_KEY,
			TB_PAM_UID
		)  ON [PRIMARY] ,
		CONSTRAINT FK_D_MOVE_CNTY_D_MOVE_CNTY_GROUP FOREIGN KEY 
		(
			D_MOVE_CNTY_GROUP_KEY
		) REFERENCES dbo.D_MOVE_CNTY_GROUP (
			D_MOVE_CNTY_GROUP_KEY
		)
	) ON [PRIMARY];
END;