IF NOT EXISTS (SELECT 1 FROM sysobjects WHERE name = 'D_PCR_SOURCE' and xtype = 'U')
BEGIN
	CREATE TABLE [dbo].[D_PCR_SOURCE](
		[VAR_PAM_UID] [bigint] NOT NULL,
		[D_PCR_SOURCE_KEY] [bigint] NOT NULL,
		[SEQ_NBR] [int] NULL,
		[D_PCR_SOURCE_GROUP_KEY] [bigint] NOT NULL,
		[LAST_CHG_TIME] [datetime] NULL,
		[VALUE] [varchar](250) NULL,
	CONSTRAINT [PK_D_PCR_SOURCE] PRIMARY KEY CLUSTERED 
	(
		[D_PCR_SOURCE_KEY] ASC,
		[VAR_PAM_UID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
	) ON [PRIMARY]

	ALTER TABLE [dbo].[D_PCR_SOURCE]  WITH CHECK ADD  CONSTRAINT [FK_D_PCR_SOURCE_D_PCR_SOURCE_GROUP] FOREIGN KEY([D_PCR_SOURCE_GROUP_KEY])
	REFERENCES [dbo].[D_PCR_SOURCE_GROUP] ([D_PCR_SOURCE_GROUP_KEY])

	ALTER TABLE [dbo].[D_PCR_SOURCE] CHECK CONSTRAINT [FK_D_PCR_SOURCE_D_PCR_SOURCE_GROUP]
END