USE [NBS_MSGOUTE];
GO

INSERT INTO [dbo].[NBS_interface]
(
    payload,
    imp_exp_ind_cd,
    record_status_cd,
    record_status_time,
    add_time,
    system_nm,
    doc_type_cd,
    filler_order_nbr,
    lab_clia,
    order_test_code,
    specimen_coll_date
)
VALUES (
    '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Container xmlns="http://www.cdc.gov/NEDSS">
    <HL7LabReport>
        <HL7MSH>
            <FieldSeparator>|</FieldSeparator>
            <EncodingCharacters>^~\&amp;</EncodingCharacters>
            <SendingApplication>
                <HL7NamespaceID>TEST_ELR_APP</HL7NamespaceID>
                <HL7UniversalID>2.16.840.1.113883.19.3.2.1</HL7UniversalID>
                <HL7UniversalIDType>ISO</HL7UniversalIDType>
            </SendingApplication>
            <SendingFacility>
                <HL7NamespaceID>CDC TEST LAB</HL7NamespaceID>
                <HL7UniversalID>99D9999999</HL7UniversalID>
                <HL7UniversalIDType>CLIA</HL7UniversalIDType>
            </SendingFacility>
            <ReceivingApplication>
                <HL7NamespaceID>NBS</HL7NamespaceID>
                <HL7UniversalID>2.16.840.1.113883.19.4.1</HL7UniversalID>
                <HL7UniversalIDType>ISO</HL7UniversalIDType>
            </ReceivingApplication>
            <ReceivingFacility>
                <HL7NamespaceID>PUBLIC HEALTH</HL7NamespaceID>
                <HL7UniversalID>2.16.840.1.113883.19.4.2</HL7UniversalID>
                <HL7UniversalIDType>ISO</HL7UniversalIDType>
            </ReceivingFacility>
            <DateTimeOfMessage>
                <year>2026</year>
                <month>05</month>
                <day>20</day>
                <hours>13</hours>
                <minutes>00</minutes>
                <seconds>00</seconds>
                <gmtOffset>-0500</gmtOffset>
            </DateTimeOfMessage>
            <Security/>
            <MessageType>
                <MessageCode>ORU</MessageCode>
                <TriggerEvent>R01</TriggerEvent>
                <MessageStructure>ORU_R01</MessageStructure>
            </MessageType>
            <MessageControlID>ELR-STEC-0002</MessageControlID>
            <ProcessingID>
                <HL7ProcessingID>T</HL7ProcessingID>
                <HL7ProcessingMode/>
            </ProcessingID>
            <VersionID>
                <HL7VersionID>2.5.1</HL7VersionID>
            </VersionID>
            <AcceptAcknowledgmentType>AL</AcceptAcknowledgmentType>
            <ApplicationAcknowledgmentType>NE</ApplicationAcknowledgmentType>
            <CountryCode>USA</CountryCode>
            <CharacterSet/>
            <MessageProfileIdentifier>
                <HL7EntityIdentifier>PHLabReport-Ack</HL7EntityIdentifier>
                <HL7NamespaceID/>
                <HL7UniversalID>2.16.840.1.113883.9.10</HL7UniversalID>
                <HL7UniversalIDType>ISO</HL7UniversalIDType>
            </MessageProfileIdentifier>
        </HL7MSH>
        <HL7SoftwareSegment>
            <SoftwareVendorOrganization>
                <HL7OrganizationName>TEST ELR GENERATOR</HL7OrganizationName>
                <HL7OrganizationNameTypeCode>L</HL7OrganizationNameTypeCode>
                <HL7IDNumber/>
                <HL7CheckDigit/>
            </SoftwareVendorOrganization>
            <SoftwareCertifiedVersionOrReleaseNumber>1.0</SoftwareCertifiedVersionOrReleaseNumber>
            <SoftwareProductName>CDC TEST DATA</SoftwareProductName>
            <SoftwareBinaryID>1.0</SoftwareBinaryID>
            <SoftwareProductInformation/>
        </HL7SoftwareSegment>
        <HL7PATIENT_RESULT>
            <PATIENT>
                <PatientIdentification>
                    <SetIDPID>
                        <HL7SequenceID>1</HL7SequenceID>
                    </SetIDPID>
                    <PatientIdentifierList>
                        <HL7IDNumber>CDC-TEST-PATIENT-001</HL7IDNumber>
                        <HL7AssigningAuthority>
                            <HL7NamespaceID>TEST_ELR_APP</HL7NamespaceID>
                            <HL7UniversalID>2.16.840.1.113883.19.3.2.1</HL7UniversalID>
                            <HL7UniversalIDType>ISO</HL7UniversalIDType>
                        </HL7AssigningAuthority>
                        <HL7IdentifierTypeCode>PI</HL7IdentifierTypeCode>
                    </PatientIdentifierList>
                    <PatientName>
                        <HL7FamilyName>
                            <HL7Surname>Swift</HL7Surname>
                        </HL7FamilyName>
                        <HL7GivenName>Taylor</HL7GivenName>
                        <HL7Degree/>
                    </PatientName>
                    <DateTimeOfBirth>
                        <year>1990</year>
                        <month>01</month>
                        <day>01</day>
                    </DateTimeOfBirth>
                    <AdministrativeSex>F</AdministrativeSex>
                    <Race>
                        <HL7Identifier>2106-3</HL7Identifier>
                        <HL7Text>White</HL7Text>
                        <HL7NameofCodingSystem>CDCREC</HL7NameofCodingSystem>
                    </Race>
                    <PatientAddress>
                        <HL7StreetAddress>
                            <HL7StreetOrMailingAddress>1600 Clifton Rd NE</HL7StreetOrMailingAddress>
                        </HL7StreetAddress>
                        <HL7City>Atlanta</HL7City>
                        <HL7StateOrProvince>GA</HL7StateOrProvince>
                        <HL7ZipOrPostalCode>30333</HL7ZipOrPostalCode>
                        <HL7Country>USA</HL7Country>
                        <HL7AddressType>H</HL7AddressType>
                    </PatientAddress>
                    <PhoneNumberHome>
                        <HL7TelecommunicationUseCode>PRN</HL7TelecommunicationUseCode>
                        <HL7TelecommunicationEquipmentType>PH</HL7TelecommunicationEquipmentType>
                        <HL7CountryCode>
                            <HL7Numeric>1</HL7Numeric>
                        </HL7CountryCode>
                        <HL7AreaCityCode>
                            <HL7Numeric>404</HL7Numeric>
                        </HL7AreaCityCode>
                        <HL7LocalNumber>
                            <HL7Numeric>6393311</HL7Numeric>
                        </HL7LocalNumber>
                        <HL7Extension/>
                    </PhoneNumberHome>
                    <SSNNumberPatient/>
                    <EthnicGroup>
                        <HL7Identifier>N</HL7Identifier>
                        <HL7Text>Not Hispanic or Latino</HL7Text>
                        <HL7NameofCodingSystem>HL70189</HL7NameofCodingSystem>
                    </EthnicGroup>
                    <BirthOrder/>
                </PatientIdentification>
            </PATIENT>
            <ORDER_OBSERVATION>
                <CommonOrder>
                    <OrderControl>RE</OrderControl>
                    <FillerOrderNumber>
                        <HL7EntityIdentifier>ORD-STEC-20260520-001</HL7EntityIdentifier>
                        <HL7NamespaceID>TEST_ELR_APP</HL7NamespaceID>
                        <HL7UniversalID>2.16.840.1.113883.19.3.2.1</HL7UniversalID>
                        <HL7UniversalIDType>ISO</HL7UniversalIDType>
                    </FillerOrderNumber>
                    <OrderStatus>CM</OrderStatus>
                    <DateTimeOfTransaction>
                        <year>2026</year>
                        <month>05</month>
                        <day>20</day>
                        <hours>13</hours>
                        <minutes>30</minutes>
                        <seconds>00</seconds>
                        <gmtOffset/>
                    </DateTimeOfTransaction>
                    <OrderingProvider>
                        <HL7IDNumber>9999999999</HL7IDNumber>
                        <HL7FamilyName>
                            <HL7Surname>Sample</HL7Surname>
                        </HL7FamilyName>
                        <HL7GivenName>Sarah</HL7GivenName>
                        <HL7NameTypeCode>NPI</HL7NameTypeCode>
                        <HL7IdentifierTypeCode/>
                    </OrderingProvider>
                    <OrderingFacilityName>
                        <HL7OrganizationName>Republic Records</HL7OrganizationName>
                        <HL7IDNumber />
                        <HL7CheckDigit />
                    </OrderingFacilityName>
                    <OrderingFacilityAddress>
                        <HL7StreetAddress>
                            <HL7StreetOrMailingAddress>CDC TEST CLINIC</HL7StreetOrMailingAddress>
                        </HL7StreetAddress>
                        <HL7City/>
                        <HL7StateOrProvince/>
                        <HL7ZipOrPostalCode/>
                        <HL7Country/>
                        <HL7AddressType/>
                    </OrderingFacilityAddress>
                    <OrderingFacilityPhoneNumber>
                        <HL7TelecommunicationUseCode/>
                        <HL7TelecommunicationEquipmentType>Atlanta</HL7TelecommunicationEquipmentType>
                        <HL7CountryCode>
                            <HL7Numeric>30333</HL7Numeric>
                        </HL7CountryCode>
                        <HL7AreaCityCode>
                            <HL7Numeric>404</HL7Numeric>
                        </HL7AreaCityCode>
                        <HL7LocalNumber>
                            <HL7Numeric>6393311</HL7Numeric>
                        </HL7LocalNumber>
                        <HL7Extension/>
                    </OrderingFacilityPhoneNumber>
                    <OrderingProviderAddress>
                        <HL7StreetAddress>
                            <HL7StreetOrMailingAddress/>
                        </HL7StreetAddress>
                        <HL7City>PH</HL7City>
                        <HL7StateOrProvince/>
                        <HL7ZipOrPostalCode>1</HL7ZipOrPostalCode>
                        <HL7Country>404</HL7Country>
                        <HL7AddressType>6393311</HL7AddressType>
                    </OrderingProviderAddress>
                </CommonOrder>
                <ObservationRequest>
                    <SetIDOBR>
                        <HL7SequenceID>1</HL7SequenceID>
                    </SetIDOBR>
                    <FillerOrderNumber>
                        <HL7EntityIdentifier>LAB-STEC-20260520-001</HL7EntityIdentifier>
                        <HL7NamespaceID>CDC TEST LAB</HL7NamespaceID>
                        <HL7UniversalID>99D9999999</HL7UniversalID>
                        <HL7UniversalIDType>CLIA</HL7UniversalIDType>
                    </FillerOrderNumber>
                    <UniversalServiceIdentifier>
                        <HL7Identifier>82195-9</HL7Identifier>
                        <HL7Text>Gastrointestinal pathogens panel - Stool by NAA with probe detection</HL7Text>
                        <HL7NameofCodingSystem>LN</HL7NameofCodingSystem>
                    </UniversalServiceIdentifier>
                    <ObservationDateTime>
                        <year>2026</year>
                        <month>05</month>
                        <day>13</day>
                        <hours>07</hours>
                        <minutes>30</minutes>
                        <seconds>00</seconds>
                        <gmtOffset>-0500</gmtOffset>
                    </ObservationDateTime>
                    <SpecimenReceivedDateTime>
                        <year>2026</year>
                        <month>05</month>
                        <day>13</day>
                        <hours>08</hours>
                        <minutes>45</minutes>
                        <seconds>00</seconds>
                        <gmtOffset/>
                    </SpecimenReceivedDateTime>
                    <OrderingProvider>
                        <HL7IDNumber>9999999999</HL7IDNumber>
                        <HL7FamilyName>
                            <HL7Surname>Sample</HL7Surname>
                        </HL7FamilyName>
                        <HL7GivenName>Sarah</HL7GivenName>
                        <HL7NameTypeCode>NPI</HL7NameTypeCode>
                        <HL7IdentifierTypeCode/>
                    </OrderingProvider>
                    <ResultsRptStatusChngDateTime>
                        <year>2026</year>
                        <month>05</month>
                        <day>13</day>
                        <hours>13</hours>
                        <minutes>00</minutes>
                        <seconds>00</seconds>
                        <gmtOffset>-0500</gmtOffset>
                    </ResultsRptStatusChngDateTime>
                    <ResultStatus>F</ResultStatus>
                    <NumberofSampleContainers/>
                </ObservationRequest>
                <PatientResultOrderObservation>
                    <OBSERVATION>
                        <ObservationResult>
                            <SetIDOBX>
                                <HL7SequenceID>1</HL7SequenceID>
                            </SetIDOBX>
                            <ValueType>CWE</ValueType>
                            <ObservationIdentifier>
                                <HL7Identifier>82203-1</HL7Identifier>
                                <HL7Text>Shiga-toxin-producing E coli stx1/stx2 [Presence] in Stool by NAA with probe detection</HL7Text>
                                <HL7NameofCodingSystem>LN</HL7NameofCodingSystem>
                            </ObservationIdentifier>
                            <ObservationValue>260373001^Detected^SCT^DET^Detected^L</ObservationValue>
                            <Probability/>
                            <ObservationResultStatus>F</ObservationResultStatus>
                            <DateTimeOftheObservation>
                                <year>2026</year>
                                <month>05</month>
                                <day>13</day>
                                <hours>07</hours>
                                <minutes>30</minutes>
                                <seconds>00</seconds>
                                <gmtOffset>-0500</gmtOffset>
                            </DateTimeOftheObservation>
                            <DateTimeOftheAnalysis>
                                <year>2026</year>
                                <month>05</month>
                                <day>13</day>
                                <hours>13</hours>
                                <minutes>00</minutes>
                                <seconds>00</seconds>
                                <gmtOffset>-0500</gmtOffset>
                            </DateTimeOftheAnalysis>
                        </ObservationResult>
                    </OBSERVATION>
                </PatientResultOrderObservation>
                <PatientResultOrderSPMObservation>
                    <SPECIMEN>
                        <SPECIMEN>
                            <SetIDSPM>
                                <HL7SequenceID>1</HL7SequenceID>
                            </SetIDSPM>
                            <SpecimenID>
                                <HL7PlacerAssignedIdentifier>
                                    <HL7EntityIdentifier/>
                                </HL7PlacerAssignedIdentifier>
                                <HL7FillerAssignedIdentifier>
                                    <HL7EntityIdentifier>SPM-STEC-20260520-001</HL7EntityIdentifier>
                                    <HL7NamespaceID>TEST_ELR_APP</HL7NamespaceID>
                                    <HL7UniversalID>2.16.840.1.113883.19.3.2.1</HL7UniversalID>
                                    <HL7UniversalIDType>ISO</HL7UniversalIDType>
                                </HL7FillerAssignedIdentifier>
                            </SpecimenID>
                            <SpecimenType>
                                <HL7Identifier>119339001</HL7Identifier>
                                <HL7Text>Stool specimen (specimen)</HL7Text>
                                <HL7NameofCodingSystem>SCT</HL7NameofCodingSystem>
                            </SpecimenType>
                            <GroupedSpecimenCount/>
                            <SpecimenCollectionDateTime>
                                <HL7RangeStartDateTime>
                                    <year>2026</year>
                                    <month>05</month>
                                    <day>13</day>
                                    <hours>07</hours>
                                    <minutes>30</minutes>
                                    <seconds>00</seconds>
                                    <gmtOffset>-0500</gmtOffset>
                                </HL7RangeStartDateTime>
                            </SpecimenCollectionDateTime>
                            <SpecimenReceivedDateTime>
                                <year>2026</year>
                                <month>05</month>
                                <day>13</day>
                                <hours>08</hours>
                                <minutes>45</minutes>
                                <seconds>00</seconds>
                                <gmtOffset>-0500</gmtOffset>
                            </SpecimenReceivedDateTime>
                            <NumberOfSpecimenContainers/>
                        </SPECIMEN>
                    </SPECIMEN>
                </PatientResultOrderSPMObservation>
            </ORDER_OBSERVATION>
        </HL7PATIENT_RESULT>
    </HL7LabReport>
</Container>
',
    N'I',                                   -- Import indicator
    N'QUEUED',                              -- Status: queued for processing
    CURRENT_TIMESTAMP,                      -- Record status time
    CURRENT_TIMESTAMP,                      -- Add time
    N'NBS',                                 -- System name
    N'11648804',                            -- ELR document type code
    N'LAB-STEC-20260520-001',      -- filler_order_nbr from OBR.FillerOrderNumber.EntityIdentifier
    N'99D9999999',              -- lab_clia from MSH.SendingFacility.UniversalID
    N'82195-9',       -- order_test_code from OBR.UniversalServiceIdentifier.Identifier
    CAST('2026-05-20 07:30:00' AS DATETIME)                     -- specimen_coll_date from SPM.SpecimenCollectionDateTime
);

