IF NOT EXISTS (SELECT 1 FROM sysobjects WHERE name = 'D_HC_PROV_TY_3' and xtype = 'U')
BEGIN
	CREATE TABLE [dbo].[D_HC_PROV_TY_3](
		[TB_PAM_UID] [bigint] NOT NULL,
		[D_HC_PROV_TY_3_KEY] [bigint] NOT NULL,
		[SEQ_NBR] [int] NULL,
		[D_HC_PROV_TY_3_GROUP_KEY] [bigint] NOT NULL,
		[LAST_CHG_TIME] [datetime] NULL,
		[VALUE] [varchar](250) NULL,
	CONSTRAINT [PK_D_HC_PROV_TY_3] PRIMARY KEY CLUSTERED 
	(
		[D_HC_PROV_TY_3_KEY] ASC,
		[TB_PAM_UID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
	) ON [PRIMARY]

	ALTER TABLE [dbo].[D_HC_PROV_TY_3]  WITH CHECK ADD  CONSTRAINT [FK_D_HC_PROV_TY_3_D_HC_PROV_TY_3_GROUP] FOREIGN KEY([D_HC_PROV_TY_3_GROUP_KEY])
	REFERENCES [dbo].[D_HC_PROV_TY_3_GROUP] ([D_HC_PROV_TY_3_GROUP_KEY])

	ALTER TABLE [dbo].[D_HC_PROV_TY_3] CHECK CONSTRAINT [FK_D_HC_PROV_TY_3_D_HC_PROV_TY_3_GROUP]
END