if NOT EXISTS (SELECT 1 FROM sysobjects WHERE name = 'D_TB_HIV' and xtype = 'U')

CREATE TABLE [dbo].[D_TB_HIV](
	[TB_PAM_UID] [bigint] NOT NULL,
	[D_TB_HIV_KEY] [bigint] NOT NULL,
	[LAST_CHG_TIME] [datetime] NULL,
	[HIV_STATE_PATIENT_NUM] [varchar](50) NULL,
	[HIV_STATUS] [varchar](50) NULL,
	[HIV_CITY_CNTY_PATIENT_NUM] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[D_TB_HIV_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]