--CNDE-2346
IF NOT EXISTS (SELECT 1
               FROM sysobjects
               WHERE name = 'D_DISEASE_SITE_GROUP'
                 and xtype = 'U')

BEGIN				 
	CREATE TABLE DBO.D_DISEASE_SITE_GROUP (
		D_DISEASE_SITE_GROUP_KEY BIGINT NOT NULL ,
		PRIMARY KEY 
		(
			D_DISEASE_SITE_GROUP_KEY
		) 
	);
END;

IF NOT EXISTS ( SELECT 1 FROM DBO.D_DISEASE_SITE_GROUP WHERE D_DISEASE_SITE_GROUP_KEY = 1 )
BEGIN
	INSERT INTO DBO.D_DISEASE_SITE_GROUP (D_DISEASE_SITE_GROUP_KEY) VALUES (1);
END;
