IF NOT EXISTS (SELECT 1 FROM sysobjects WHERE name = 'd_out_of_cntry_group' and xtype = 'U')
BEGIN
	CREATE TABLE [dbo].[D_OUT_OF_CNTRY_GROUP](
		[D_OUT_OF_CNTRY_GROUP_KEY] [bigint] NOT NULL,
	CONSTRAINT [PK_D_OUT_OF_CNTRY_GROUP] PRIMARY KEY CLUSTERED 
	(
		[D_OUT_OF_CNTRY_GROUP_KEY] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
	) ON [PRIMARY]
END

