IF NOT EXISTS (SELECT 1
               FROM sysobjects
               WHERE name = 'D_MOVED_WHERE'
                 and xtype = 'U')

BEGIN				 
	CREATE TABLE DBO.D_MOVED_WHERE (
		TB_PAM_UID BIGINT NOT NULL ,
		D_MOVED_WHERE_KEY BIGINT NOT NULL ,
		SEQ_NBR INT NULL ,
		D_MOVED_WHERE_GROUP_KEY BIGINT NOT NULL ,
		LAST_CHG_TIME DATETIME NULL ,
		VALUE VARCHAR (250) NULL ,
		CONSTRAINT PK_D_MOVED_WHERE PRIMARY KEY  CLUSTERED 
		(
			D_MOVED_WHERE_KEY,
			TB_PAM_UID
		)  ON [PRIMARY] ,
		CONSTRAINT FK_D_MOVED_WHERE_D_MOVED_WHERE_GROUP FOREIGN KEY 
		(
			D_MOVED_WHERE_GROUP_KEY
		) REFERENCES dbo.D_MOVED_WHERE_GROUP (
			D_MOVED_WHERE_GROUP_KEY
		)
	) ON [PRIMARY];
END;