IF NOT EXISTS (SELECT 1 FROM sysobjects WHERE name = 'nrt_d_smr_exam_ty_key' and xtype = 'U')
BEGIN
    CREATE TABLE [dbo].[nrt_d_smr_exam_ty_key](
        [D_SMR_EXAM_TY_KEY] [bigint] IDENTITY (2,1) NOT NULL,
        [NBS_CASE_ANSWER_UID] [bigint] NOT NULL,
        [TB_PAM_UID] [bigint] NOT NULL,
        [created_dttm] DATETIME2 DEFAULT GETDATE(),
        [updated_dttm] DATETIME2 DEFAULT GETDATE(),
    CONSTRAINT [NRT_D_SMR_EXAM_TY_KEY_PK] PRIMARY KEY CLUSTERED 
	(
		[D_SMR_EXAM_TY_KEY] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
	) ON [PRIMARY];
	DECLARE @max bigint = (SELECT ISNULL(MAX(D_SMR_EXAM_TY_KEY)+1, 2) FROM dbo.D_SMR_EXAM_TY);
	DBCC CHECKIDENT ('dbo.nrt_d_smr_exam_ty_key', RESEED, @max);
END

