IF NOT EXISTS (SELECT 1
               FROM sysobjects
               WHERE name = 'D_RASH_LOC_GEN'
                 and xtype = 'U')
BEGIN	
	CREATE TABLE DBO.D_RASH_LOC_GEN (
		VAR_PAM_UID BIGINT NOT NULL ,
		D_RASH_LOC_GEN_KEY BIGINT NOT NULL ,
		SEQ_NBR INT NULL ,
		D_RASH_LOC_GEN_GROUP_KEY BIGINT NOT NULL ,
		LAST_CHG_TIME           DATETIME  NULL,
		VALUE VARCHAR (250) NULL ,
		CONSTRAINT PK_D_RASH_LOC_GEN PRIMARY KEY  CLUSTERED 
		(
			D_RASH_LOC_GEN_KEY,
			VAR_PAM_UID
		)  ON [PRIMARY] ,
		CONSTRAINT FK_D_RASH_LOC_GEN_D_RASH_LOC_GEN_GROUP FOREIGN KEY 
		(
			D_RASH_LOC_GEN_GROUP_KEY
		) REFERENCES dbo.D_RASH_LOC_GEN_GROUP (
			D_RASH_LOC_GEN_GROUP_KEY
		)
	) ON [PRIMARY];
END;