-- ==========================================
-- LAB_TEST column fixes
-- The development database never applied an RDB migration from 6.0.8 that adjust the
-- length of some columns.
-- 
-- Migration: https://github.com/cdcent/NEDSSDB/blob/main/deprecated/db/Disk_Database/WINDOWS/DB%20Setup%20Scripts-Release%20Upgrade/MS%20SQL/R6.0.8/RDB/01_6.0.8_Migrate_RDB_Structure.sql
-- ==========================================

USE RDB;
GO

/*
ND-18353 TST: Verify Updates to ELR process and DB for OBX 18.1
*/
ALTER TABLE RDB.DBO.LAB_TEST ALTER COLUMN TEST_METHOD_CD VARCHAR(199);
GO

ALTER TABLE RDB.DBO.LAB_TEST ALTER COLUMN TEST_METHOD_CD_DESC VARCHAR(199);
GO

/*ND-18817 DB: Update act_id.root_extension_txt to 199 char*/

ALTER TABLE RDB.DBO.S_INVESTIGATION ALTER COLUMN LEGACY_CASE_ID VARCHAR(199);
GO
ALTER TABLE RDB.DBO.S_INVESTIGATION ALTER COLUMN CITY_COUNTY_CASE_NBR VARCHAR(
    199
);
GO
ALTER TABLE RDB.DBO.S_INVESTIGATION ALTER COLUMN INV_STATE_CASE_ID VARCHAR(199);
GO
ALTER TABLE RDB.DBO.INVESTIGATION ALTER COLUMN LEGACY_CASE_ID VARCHAR(199);
GO
ALTER TABLE RDB.DBO.INVESTIGATION ALTER COLUMN CITY_COUNTY_CASE_NBR VARCHAR(
    199
);
GO
ALTER TABLE RDB.DBO.INVESTIGATION ALTER COLUMN INV_STATE_CASE_ID VARCHAR(199);
GO
ALTER TABLE RDB.DBO.LAB_TEST ALTER COLUMN ACCESSION_NBR VARCHAR(199);
GO
ALTER TABLE RDB.DBO.LAB100 ALTER COLUMN ACCESSION_NBR VARCHAR(199);
GO
