create or alter view dbo.v_nrt_d_inv_repeat_blockdata as
select
	BLOCK_NM,
	RDB_COLUMN_NM,
	USER_DEFINED_COLUMN_NM,
	INVESTIGATION_FORM_CD
FROM
	NBS_ODSE..NBS_RDB_METADATA
INNER JOIN NBS_ODSE..NBS_UI_METADATA ON
	NBS_RDB_METADATA.NBS_UI_METADATA_UID = NBS_UI_METADATA.NBS_UI_METADATA_UID
WHERE
	BLOCK_NM IS NOT NULL
	AND USER_DEFINED_COLUMN_NM != ''
	and USER_DEFINED_COLUMN_NM IS NOT NULL
	AND RDB_TABLE_NM = 'D_INVESTIGATION_REPEAT'
	and (code_set_group_id >0
		OR data_type in ( 'Coded' , 'Text', 'text', 'TEXT', 'CODED') )
;
