package gov.cdc.etldatapipeline.integration.unit;

import static org.assertj.core.api.Assertions.assertThat;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import gov.cdc.etldatapipeline.organization.model.dto.org.OrganizationSp;
import gov.cdc.etldatapipeline.organization.repository.OrgRepository;
import java.util.ArrayList;
import java.util.Set;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.jdbc.core.simple.JdbcClient;

class OrganizationEventTest extends UnitTest {

  private final OrgRepository orgRepository;
  private final JdbcClient client;
  private final ObjectMapper mapper = new ObjectMapper().enable(SerializationFeature.INDENT_OUTPUT);

  OrganizationEventTest(
      @Autowired final OrgRepository orgRepository, @Qualifier("adminClient") JdbcClient client) {
    this.orgRepository = orgRepository;
    this.client = client;
  }

  private static final String INSERT_ORGANIZATION_DATA =
      """
      -- Entity
      INSERT INTO [dbo].[entity]
                  ([entity_uid],
                   [class_cd])
      VALUES      (-1000,
                   N'ORG');

      --- Organization
      INSERT INTO [dbo].[organization]
                  ([organization_uid],
                   [add_reason_cd],
                   [add_time],
                   [add_user_id],
                   [cd],
                   [cd_desc_txt],
                   [description],
                   [duration_amt],
                   [duration_unit_cd],
                   [from_time],
                   [last_chg_reason_cd],
                   [last_chg_time],
                   [last_chg_user_id],
                   [local_id],
                   [record_status_cd],
                   [record_status_time],
                   [standard_industry_class_cd],
                   [standard_industry_desc_txt],
                   [status_cd],
                   [status_time],
                   [to_time],
                   [user_affiliation_txt],
                   [display_nm],
                   [street_addr1],
                   [street_addr2],
                   [city_cd],
                   [city_desc_txt],
                   [state_cd],
                   [cnty_cd],
                   [cntry_cd],
                   [zip_cd],
                   [phone_nbr],
                   [phone_cntry_cd],
                   [version_ctrl_nbr],
                   [electronic_ind],
                   [edx_ind])
      VALUES      (-1000,
                   NULL,
                   '2026-04-03 14:43:38.510',
                   '9999',
                   NULL,
                   NULL,
                   N'Added for testing',
                   NULL,
                   NULL,
                   NULL,
                   NULL,
                   '2026-04-03 14:43:38.510',
                   '9999',
                   'ORG-1000GA01',
                   N'ACTIVE',
                   '2026-04-03 14:43:38.510',
                   N'62',
                   NULL,
                   N'A',
                   '2026-04-03 14:43:38.510',
                   NULL,
                   NULL,
                   N'Wellstar Cobb Medical Center',
                   NULL,
                   NULL,
                   NULL,
                   NULL,
                   NULL,
                   NULL,
                   NULL,
                   NULL,
                   NULL,
                   NULL,
                   '1',
                   N'N',
                   NULL);

      -- Entity_id (Quick entry code, Identification)
      INSERT INTO [dbo].[entity_id]
                  ([entity_uid],
                   [entity_id_seq],
                   [add_reason_cd],
                   [add_time],
                   [add_user_id],
                   [assigning_authority_cd],
                   [assigning_authority_desc_txt],
                   [duration_amt],
                   [duration_unit_cd],
                   [effective_from_time],
                   [effective_to_time],
                   [last_chg_reason_cd],
                   [last_chg_time],
                   [last_chg_user_id],
                   [record_status_cd],
                   [record_status_time],
                   [root_extension_txt],
                   [status_cd],
                   [status_time],
                   [type_cd],
                   [type_desc_txt],
                   [user_affiliation_txt],
                   [valid_from_time],
                   [valid_to_time],
                   [as_of_date],
                   [assigning_authority_id_type])
      VALUES      (-1000,
                   '2',
                   NULL,
                   '2026-04-03 14:43:38.407',
                   NULL,
                   NULL,
                   NULL,
                   NULL,
                   NULL,
                   NULL,
                   NULL,
                   NULL,
                   '2026-04-03 14:43:38.407',
                   NULL,
                   N'ACTIVE',
                   '2026-04-03 14:43:38.407',
                   N'99',
                   N'A',
                   '2026-04-03 14:43:38.407',
                   N'QEC',
                   N'Quick Entry Code',
                   NULL,
                   NULL,
                   NULL,
                   NULL,
                   NULL),
                  (-1000,
                   '1',
                   NULL,
                   '2026-04-03 14:43:38.407',
                   NULL,
                   N'CMS',
                   N'CMS Provider',
                   NULL,
                   NULL,
                   NULL,
                   NULL,
                   NULL,
                   '2026-04-03 14:43:38.407',
                   NULL,
                   N'ACTIVE',
                   NULL,
                   N'110035',
                   N'A',
                   '2026-04-03 14:43:38.577',
                   N'FI',
                   N'',
                   NULL,
                   NULL,
                   NULL,
                   NULL,
                   N'L');

      -- Entity_locator_participation (Phone, Address)
      INSERT INTO [dbo].[entity_locator_participation]
                  ([entity_uid],
                   [locator_uid],
                   [add_reason_cd],
                   [add_time],
                   [add_user_id],
                   [cd],
                   [cd_desc_txt],
                   [class_cd],
                   [duration_amt],
                   [duration_unit_cd],
                   [from_time],
                   [last_chg_reason_cd],
                   [last_chg_time],
                   [last_chg_user_id],
                   [locator_desc_txt],
                   [record_status_cd],
                   [record_status_time],
                   [status_cd],
                   [status_time],
                   [to_time],
                   [use_cd],
                   [user_affiliation_txt],
                   [valid_time_txt],
                   [version_ctrl_nbr],
                   [as_of_date])
      VALUES      (-1000,
                   -1001,
                   NULL,
                   NULL,
                   NULL,
                   N'PH',
                   NULL,
                   N'TELE',
                   NULL,
                   NULL,
                   NULL,
                   NULL,
                   '2026-04-03 14:43:38.510',
                   '9999',
                   N'',
                   N'ACTIVE',
                   '2026-04-03 14:43:38.510',
                   N'A',
                   '2026-04-03 14:43:38.510',
                   NULL,
                   N'WP',
                   NULL,
                   NULL,
                   '1',
                   NULL),
                  (-1000,
                   -1002,
                   NULL,
                   NULL,
                   NULL,
                   N'O',
                   N'',
                   N'PST',
                   NULL,
                   NULL,
                   NULL,
                   NULL,
                   '2026-04-03 14:43:38.510',
                   '9999',
                   N'Emergency room address',
                   N'ACTIVE',
                   '2026-04-03 14:43:38.510',
                   N'A',
                   '2026-04-03 14:43:38.510',
                   NULL,
                   N'WP',
                   NULL,
                   NULL,
                   '1',
                   NULL);

      -- Postal_locator
      INSERT INTO [dbo].[postal_locator]
                  ([postal_locator_uid],
                   [add_reason_cd],
                   [add_time],
                   [add_user_id],
                   [census_block_cd],
                   [census_minor_civil_division_cd],
                   [census_track_cd],
                   [city_cd],
                   [city_desc_txt],
                   [cntry_cd],
                   [cntry_desc_txt],
                   [cnty_cd],
                   [cnty_desc_txt],
                   [last_chg_reason_cd],
                   [last_chg_time],
                   [last_chg_user_id],
                   [msa_congress_district_cd],
                   [record_status_cd],
                   [record_status_time],
                   [region_district_cd],
                   [state_cd],
                   [street_addr1],
                   [street_addr2],
                   [user_affiliation_txt],
                   [zip_cd],
                   [geocode_match_ind],
                   [within_city_limits_ind],
                   [census_tract])
      VALUES      (-1002,
                   NULL,
                   NULL,
                   NULL,
                   NULL,
                   NULL,
                   NULL,
                   NULL,
                   N'Austell',
                   N'840',
                   NULL,
                   N'13067',
                   NULL,
                   NULL,
                   NULL,
                   NULL,
                   NULL,
                   NULL,
                   NULL,
                   NULL,
                   N'13',
                   N'3950 Austell Rd SW',
                   N'',
                   NULL,
                   N'30106',
                   NULL,
                   NULL,
                   NULL);

      -- Tele_locator
      INSERT INTO [dbo].[tele_locator]
                  ([tele_locator_uid],
                   [add_reason_cd],
                   [add_time],
                   [add_user_id],
                   [cntry_cd],
                   [email_address],
                   [extension_txt],
                   [last_chg_reason_cd],
                   [last_chg_time],
                   [last_chg_user_id],
                   [phone_nbr_txt],
                   [record_status_cd],
                   [record_status_time],
                   [url_address],
                   [user_affiliation_txt])
      VALUES      (-1001,
                   NULL,
                   NULL,
                   NULL,
                   N'1',
                   N'',
                   N'',
                   NULL,
                   NULL,
                   NULL,
                   N'770-732-4000',
                   NULL,
                   NULL,
                   N'',
                   NULL);

      -- Organization_name
      INSERT INTO [dbo].[organization_name]
                  ([organization_uid],
                   [organization_name_seq],
                   [nm_txt],
                   [nm_use_cd],
                   [record_status_cd],
                   [default_nm_ind])
      VALUES      (-1000,
                   '0',
                   N'Wellstar Cobb Medical Center',
                   N'L',
                   N'ACTIVE',
                   NULL);

      -- Role (Hospital, Laboratory)
      INSERT INTO [dbo].[role]
                  ([subject_entity_uid],
                   [cd],
                   [role_seq],
                   [add_reason_cd],
                   [add_time],
                   [add_user_id],
                   [cd_desc_txt],
                   [effective_duration_amt],
                   [effective_duration_unit_cd],
                   [effective_from_time],
                   [effective_to_time],
                   [last_chg_reason_cd],
                   [last_chg_time],
                   [last_chg_user_id],
                   [record_status_cd],
                   [record_status_time],
                   [scoping_class_cd],
                   [scoping_entity_uid],
                   [scoping_role_cd],
                   [scoping_role_seq],
                   [status_cd],
                   [status_time],
                   [subject_class_cd],
                   [user_affiliation_txt])
      VALUES      (-1000,
                   N'LAB',
                   '2',
                   NULL,
                   '2026-04-03 14:43:38.617',
                   NULL,
                   NULL,
                   NULL,
                   NULL,
                   '2026-04-03 14:43:38.617',
                   '2026-04-03 14:43:38.617',
                   NULL,
                   '2026-04-03 14:43:38.510',
                   '9999',
                   N'ACTIVE',
                   '2026-04-03 14:43:38.510',
                   NULL,
                   NULL,
                   NULL,
                   NULL,
                   N'A',
                   '2026-04-03 14:43:38.510',
                   N'ORG',
                   NULL),
                  (-1000,
                   N'HOSP',
                   '1',
                   NULL,
                   '2026-04-03 14:43:38.610',
                   NULL,
                   NULL,
                   NULL,
                   NULL,
                   '2026-04-03 14:43:38.610',
                   '2026-04-03 14:43:38.610',
                   NULL,
                   '2026-04-03 14:43:38.510',
                   '9999',
                   N'ACTIVE',
                   '2026-04-03 14:43:38.510',
                   NULL,
                   NULL,
                   NULL,
                   NULL,
                   N'A',
                   '2026-04-03 14:43:38.510',
                   N'ORG',
                   NULL);
            """;

  private static final String EXPECTED =
      """
        {
        "organizationUid" : -1000,
        "description" : "Added for testing",
        "cd" : null,
        "electronicInd" : "N",
        "recordStatusCd" : "ACTIVE",
        "recordStatusTime" : "2026-04-03 14:43:38.51",
        "statusCd" : "A",
        "statusTime" : "2026-04-03 14:43:38.51",
        "localId" : "ORG-1000GA01",
        "versionCtrlNbr" : "1",
        "edxInd" : null,
        "standIndClass" : "Health Care and Social Assistance",
        "addUserName" : null,
        "lastChgUserName" : null,
        "addUserId" : 9999,
        "lastChgUserId" : 9999,
        "addTime" : "2026-04-03 14:43:38.51",
        "lastChgTime" : "2026-04-03 14:43:38.51",
        "organizationName" : "[{\\"on_org_uid\\":-1000,\\"organization_name\\":\\"Wellstar Cobb Medical Center\\"}]",
        "organizationAddress" : "[{\\"addr_elp_cd\\":\\"O\\",\\"addr_elp_use_cd\\":\\"WP\\",\\"addr_pl_uid\\":-1002,\\"street_addr1\\":\\"3950 Austell Rd SW\\",\\"street_addr2\\":\\"\\",\\"city\\":\\"Austell\\",\\"zip\\":\\"30106\\",\\"cnty_cd\\":\\"13067\\",\\"state\\":\\"13\\",\\"cntry_cd\\":\\"840\\",\\"state_desc\\":\\"Georgia\\",\\"county\\":\\"Cobb County\\",\\"within_city_limits_ind\\":null,\\"country\\":\\"United States\\",\\"address_comments\\":\\"Emergency room address\\",\\"county_desc\\":\\"Cobb County\\"}]",
        "organizationTelephone" : "[{\\"ph_tl_uid\\":-1001,\\"ph_elp_cd\\":\\"PH\\",\\"ph_elp_use_cd\\":\\"WP\\",\\"telephone_nbr\\":\\"770-732-4000\\",\\"extension_txt\\":\\"\\",\\"email_address\\":\\"\\",\\"phone_comments\\":\\"\\"}]",
        "organizationFax" : null,
        "organizationEntityId" : "[{\\"entity_uid\\":-1000,\\"type_cd\\":\\"FI\\",\\"record_status_cd\\":\\"ACTIVE\\",\\"root_extension_txt\\":\\"110035\\",\\"entity_id_seq\\":1,\\"assigning_authority_cd\\":\\"CMS\\",\\"facility_id_auth\\":\\"CMS Provider\\"},{\\"entity_uid\\":-1000,\\"type_cd\\":\\"QEC\\",\\"record_status_cd\\":\\"ACTIVE\\",\\"root_extension_txt\\":\\"99\\",\\"entity_id_seq\\":2,\\"assigning_authority_cd\\":null,\\"facility_id_auth\\":null}]"
      }
        """;

  @Test
  void testOrganizationEvent() throws JsonProcessingException {
    // Insert organization data
    client.sql(INSERT_ORGANIZATION_DATA).update();

    // Call sp_organization_event
    Set<OrganizationSp> organizationSet = orgRepository.computeAllOrganizations("-1000");

    // Validate result
    assertThat(organizationSet).hasSize(1);
    OrganizationSp organizationSp = new ArrayList<>(organizationSet).get(0);

    String actual = mapper.writeValueAsString(organizationSp);
    // Serialize / deserialize expected to match formatting of actual
    String formattedExpected = mapper.writeValueAsString(mapper.readValue(EXPECTED, Object.class));

    assertThat(actual).isEqualTo(formattedExpected);
  }
}
