IF NOT EXISTS (SELECT 1 FROM sysobjects WHERE name = 'D_GT_12_REAS' and xtype = 'U')
BEGIN
	CREATE TABLE [dbo].[D_GT_12_REAS](
		[TB_PAM_UID] [bigint] NOT NULL,
		[D_GT_12_REAS_KEY] [bigint] NOT NULL,
		[SEQ_NBR] [int] NULL,
		[D_GT_12_REAS_GROUP_KEY] [bigint] NOT NULL,
		[LAST_CHG_TIME] [datetime] NULL,
		[VALUE] [varchar](250) NULL,
	CONSTRAINT [PK_D_GT_12_REAS] PRIMARY KEY CLUSTERED 
	(
		[D_GT_12_REAS_KEY] ASC,
		[TB_PAM_UID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
	) ON [PRIMARY]

	ALTER TABLE [dbo].[D_GT_12_REAS]  WITH CHECK ADD  CONSTRAINT [FK_D_GT_12_REAS_D_GT_12_REAS_GROUP] FOREIGN KEY([D_GT_12_REAS_GROUP_KEY])
	REFERENCES [dbo].[D_GT_12_REAS_GROUP] ([D_GT_12_REAS_GROUP_KEY])

	ALTER TABLE [dbo].[D_GT_12_REAS] CHECK CONSTRAINT [FK_D_GT_12_REAS_D_GT_12_REAS_GROUP]
END