IF NOT EXISTS (SELECT 1
               FROM sysobjects
               WHERE name = 'D_MOVED_WHERE_GROUP'
                 and xtype = 'U')

BEGIN				 
	CREATE TABLE DBO.D_MOVED_WHERE_GROUP (
		D_MOVED_WHERE_GROUP_KEY BIGINT NOT NULL ,
		CONSTRAINT PK_D_MOVED_WHERE_GROUP PRIMARY KEY CLUSTERED 
		(
			D_MOVED_WHERE_GROUP_KEY
		)  ON [PRIMARY ]
	) ON [PRIMARY];
END;