IF NOT EXISTS (SELECT 1 FROM sysobjects WHERE name = 'D_SMR_EXAM_TY' and xtype = 'U')
BEGIN
	CREATE TABLE [dbo].[D_SMR_EXAM_TY](
		[TB_PAM_UID] [bigint] NOT NULL,
		[D_SMR_EXAM_TY_KEY] [bigint] NOT NULL,
		[SEQ_NBR] [int] NULL,
		[D_SMR_EXAM_TY_GROUP_KEY] [bigint] NOT NULL,
		[LAST_CHG_TIME] [datetime] NULL,
		[VALUE] [varchar](250) NULL,
	CONSTRAINT [PK_D_SMR_EXAM_TY] PRIMARY KEY CLUSTERED 
	(
		[D_SMR_EXAM_TY_KEY] ASC,
		[TB_PAM_UID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
	) ON [PRIMARY]

	ALTER TABLE [dbo].[D_SMR_EXAM_TY]  WITH CHECK ADD  CONSTRAINT [FK_D_SMR_EXAM_TY_D_SMR_EXAM_TY_GROUP] FOREIGN KEY([D_SMR_EXAM_TY_GROUP_KEY])
	REFERENCES [dbo].[D_SMR_EXAM_TY_GROUP] ([D_SMR_EXAM_TY_GROUP_KEY])

	ALTER TABLE [dbo].[D_SMR_EXAM_TY] CHECK CONSTRAINT [FK_D_SMR_EXAM_TY_D_SMR_EXAM_TY_GROUP]
END