IF NOT EXISTS (SELECT 1 FROM sysobjects WHERE name = 'D_PCR_SOURCE_GROUP' and xtype = 'U') 
BEGIN
	CREATE TABLE [dbo].[D_PCR_SOURCE_GROUP](
		[D_PCR_SOURCE_GROUP_KEY] [bigint] NOT NULL,
	CONSTRAINT [PK_D_PCR_SOURCE_GROUP] PRIMARY KEY CLUSTERED 
	(
		[D_PCR_SOURCE_GROUP_KEY] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
	) ON [PRIMARY]
END
