IF NOT EXISTS (SELECT 1
               FROM sysobjects
               WHERE name = 'COVID_CONTACT_DATAMART'
                 and xtype = 'U')
    BEGIN
        CREATE TABLE dbo.COVID_CONTACT_DATAMART
        (
            SRC_PATIENT_FIRST_NAME        varchar(50)   NULL,
            SRC_PATIENT_MIDDLE_NAME       varchar(50)   NULL,
            SRC_PATIENT_LAST_NAME         varchar(50)   NULL,
            SRC_PATIENT_DOB               datetime      NULL,
            SRC_PATIENT_AGE_REPORTED      varchar(10)   NULL,
            SRC_PATIENT_AGE_RPTD_UNIT     varchar(20)   NULL,
            SRC_PATIENT_CURRENT_SEX       char(1)       NULL,
            SRC_PATIENT_DECEASED_IND      varchar(20)   NULL,
            SRC_PATIENT_DECEASED_DT       datetime      NULL,
            SRC_PATIENT_STREET_ADDR_1     varchar(100)  NULL,
            SRC_PATIENT_STREET_ADDR_2     varchar(100)  NULL,
            SRC_PATIENT_CITY              varchar(100)  NULL,
            SRC_PATIENT_STATE             varchar(20)   NULL,
            SRC_PATIENT_ZIP               varchar(20)   NULL,
            SRC_PATIENT_COUNTY            varchar(20)   NULL,
            SRC_PATIENT_COUNTRY           varchar(20)   NULL,
            SRC_INV_JURISDICTION_NM       varchar(255)  NULL,
            SRC_INV_START_DT              datetime      NULL,
            SRC_INV_STATUS                varchar(20)   NULL,
            SRC_INV_STATE_CASE_ID         varchar(199)  NULL,
            SRC_INV_LEGACY_CASE_ID        varchar(199)  NULL,
            SRC_INV_CDC_ASSIGNED_ID       varchar(2000) NULL,
            SRC_INV_RPTNG_CNTY            varchar(2000) NULL,
            SRC_INV_HSPTLIZD_IND          varchar(20)   NULL,
            SRC_INV_DIE_FRM_ILLNESS_IND   varchar(20)   NULL,
            SRC_INV_DEATH_DT              datetime      NULL,
            SRC_INV_CASE_STATUS           varchar(20)   NULL,
            SRC_INV_SYMPTOMATIC           varchar(2000) NULL,
            SRC_INV_ILLNESS_ONSET_DT      datetime      NULL,
            SRC_INV_ILLNESS_END_DT        datetime      NULL,
            SRC_INV_SYMPTOM_STATUS        varchar(2000) NULL,
            SRC_CTT_INV_PRIORITY          varchar(50)   NULL,
            SRC_CTT_INV_INFECTIOUS_FRM_DT datetime      NULL,
            SRC_CTT_INV_INFECTIOUS_TO_DT  datetime      NULL,
            SRC_CTT_INV_STATUS            varchar(50)   NULL,
            SRC_CTT_INV_COMMENTS          varchar(8000) NULL,
            CR_JURISDICTION_NM            varchar(255)  NULL,
            CR_STATUS                     varchar(20)   NULL,
            CR_PRIORITY                   varchar(20)   NULL,
            CR_INV_FIRST_NAME             varchar(50)   NULL,
            CR_INV_LAST_NAME              varchar(50)   NULL,
            CR_INV_ASSIGNED_DT            datetime      NULL,
            CR_DISPOSITION                varchar(20)   NULL,
            CR_DISPO_DT                   datetime      NULL,
            CR_NAMED_ON_DT                datetime      NULL,
            CR_RELATIONSHIP               varchar(20)   NULL,
            CR_HEALTH_STATUS              varchar(20)   NULL,
            CR_EXPOSURE_TYPE              varchar(2000) NULL,
            CR_EXPOSURE_SITE_TY           varchar(2000) NULL,
            CR_FIRST_EXPOSURE_DT          varchar(2000) NULL,
            CR_LAST_EXPOSURE_DT           varchar(2000) NULL,
            CR_SYMP_IND                   varchar(20)   NULL,
            CR_SYMP_ONSET_DT              datetime      NULL,
            CR_RISK_IND                   varchar(20)   NULL,
            CR_RISK_NOTES                 varchar(8000) NULL,
            CR_EVAL_COMPLETED             varchar(20)   NULL,
            CR_EVAL_DT                    datetime      NULL,
            CR_EVAL_NOTES                 varchar(8000) NULL,
            CTT_PATIENT_FIRST_NAME        varchar(50)   NULL,
            CTT_PATIENT_MIDDLE_NAME       varchar(50)   NULL,
            CTT_PATIENT_LAST_NAME         varchar(50)   NULL,
            CTT_PATIENT_DOB               datetime      NULL,
            CTT_PATIENT_AGE_REPORTED      varchar(10)   NULL,
            CTT_PATIENT_AGE_RPTD_UNIT     varchar(20)   NULL,
            CTT_PATIENT_CURRENT_SEX       char(1)       NULL,
            CTT_PATIENT_DECEASED_IND      varchar(20)   NULL,
            CTT_PATIENT_DECEASED_DT       datetime      NULL,
            CTT_PATIENT_STREET_ADDR_1     varchar(100)  NULL,
            CTT_PATIENT_STREET_ADDR_2     varchar(100)  NULL,
            CTT_PATIENT_CITY              varchar(100)  NULL,
            CTT_PATIENT_STATE             varchar(20)   NULL,
            CTT_PATIENT_ZIP               varchar(20)   NULL,
            CTT_PATIENT_COUNTY            varchar(20)   NULL,
            CTT_PATIENT_COUNTRY           varchar(20)   NULL,
            CTT_PATIENT_TEL_HOME          varchar(20)   NULL,
            CTT_PATIENT_PHONE_WORK        varchar(20)   NULL,
            CTT_PATIENT_PHONE_EXT_WORK    varchar(20)   NULL,
            CTT_PATIENT_TEL_CELL          varchar(20)   NULL,
            CTT_PATIENT_EMAIL             varchar(100)  NULL,
            CTT_INV_JURISDICTION_NM       varchar(255)  NULL,
            CTT_INV_START_DT              datetime      NULL,
            CTT_INV_STATUS                varchar(20)   NULL,
            CTT_INV_STATE_CASE_ID         varchar(199)  NULL,
            CTT_INV_LEGACY_CASE_ID        varchar(199)  NULL,
            CTT_INV_CDC_ASSIGNED_ID       varchar(2000) NULL,
            CTT_INV_RPTNG_CNTY            varchar(2000) NULL,
            CTT_INV_HSPTLIZD_IND          varchar(20)   NULL,
            CTT_INV_DIE_FRM_ILLNESS_IND   varchar(20)   NULL,
            CTT_INV_DEATH_DT              datetime      NULL,
            CTT_INV_CASE_STATUS           varchar(20)   NULL,
            CTT_INV_SYMPTOMATIC           varchar(2000) NULL,
            CTT_INV_ILLNESS_ONSET_DT      datetime      NULL,
            CTT_INV_ILLNESS_END_DT        datetime      NULL,
            CTT_INV_SYMPTOM_STATUS        varchar(2000) NULL
        );
    END

--TEMPORARY STOPGAP FOR GREENFIELD DATABASE LIQUIBASE BUILD FAILURE
IF NOT EXISTS(SELECT 1 FROM sys.columns WHERE name = N'CONTACT_UID' AND object_id = Object_ID(N'COVID_CONTACT_DATAMART'))
    BEGIN
        ALTER TABLE COVID_CONTACT_DATAMART
            ADD CONTACT_UID bigint NOT NULL;
    END;