IF NOT EXISTS (SELECT 1 FROM sysobjects WHERE name = 'COVID_LAB_CELR_DATAMART' and xtype = 'U')
BEGIN
    CREATE TABLE [dbo].[COVID_LAB_CELR_DATAMART](
            COVID_LAB_DATAMART_KEY bigint NOT NULL,
        	Testing_lab_accession_number varchar(199) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        	Testing_lab_specimen_ID varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        	Submitter_unique_sample_ID int NULL,
        	Submitter_sample_ID_assigner int NULL,
        	Testing_lab_name varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        	Testing_lab_ID varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        	Testing_lab_ID_type varchar(4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        	Testing_lab_street_address varchar(202) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        	Testing_lab_city varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        	Testing_lab_state varchar(2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        	Testing_lab_zip_code varchar(6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        	Patient_ID varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        	Patient_ID_assigner varchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
        	Patient_ID_type varchar(2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
        	Patient_DOB datetime NULL,
        	Patient_gender char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        	Patient_race varchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        	Patient_city varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        	Patient_state varchar(4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        	Patient_zip_code varchar(6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        	Patient_county varchar(21) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        	Patient_ethnicity varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        	Patient_Age varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        	Patient_Age_Units varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        	Illness_Onset_Date varchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        	Pregnant varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        	Symptomatic_for_disease varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        	Patient_location int NULL,
        	Employed_in_high_risk_setting int NULL,
        	Public_Health_Case_ID varchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        	Specimen_type_code varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        	Specimen_type_description varchar(250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        	Specimen_type_code_system varchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        	Specimen_type_free_text varchar(250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        	Specimen_collection_date_time varchar(23) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        	Specimen_received_date_time int NULL,
        	Ordering_entity_name varchar(4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
        	Ordering_provider_last_name varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        	Ordering_provider_first_name varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        	Ordering_provider_street varchar(202) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        	Ordering_provider_city varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        	Ordering_provider_state varchar(4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        	Ordering_provider_zip_code varchar(6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        	Ordering_facility_name varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        	Ordering_facility_street varchar(202) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        	Ordering_facility_city varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        	Ordering_facility_state varchar(4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        	Ordering_facility_zip_code varchar(6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        	Ordering_facility_phone_number varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        	Order_result_status varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        	Date_result_released datetime NULL,
        	Ordered_test_code varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        	Ordered_test_description varchar(250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        	Ordered_test_code_system varchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        	Test_performed_code varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        	Test_performed_description varchar(250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        	Test_performed_code_system varchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        	Test_result_coded varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        	Test_result_description varchar(250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        	Test_result_code_system varchar(300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        	Test_Result_free_text varchar(250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        	Test_result_comparator varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        	Test_result_number numeric(15,5) NULL,
        	Test_result_number_separator varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        	Test_result_number2 numeric(15,5) NULL,
        	Test_result_units varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        	Reference_range varchar(41) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        	Abnormal_flag varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        	Test_method_description int NULL,
        	Test_result_status varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        	Test_date datetime NULL,
        	Reporting_facility_name varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        	Reporting_facility_ID varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        	Report_facil_data_source_app int NULL,
        	csv_file_version_no varchar(11) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
        	File_created_date datetime NOT NULL,
        	Employed_in_healthcare varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        	First_test varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        	Hospitalized varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        	ICU varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        	Resident_congregate_setting varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        	Most_recent_test_date int NULL,
        	Most_recent_test_result int NULL,
        	Most_recent_test_type int NULL,
        	Disease_symptoms int NULL,
        	Patient_occupation int NULL,
        	Patient_residency_type int NULL,
        	Ordering_facility_county varchar(21) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        	Ordering_provider_county varchar(21) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        	Ordering_provider_ID varchar(199) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        	Patient_death_date datetime NULL,
        	Patient_death_indicator varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        	Specimen_source_site_code varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        	Specimen_source_site_code_sys int NULL,
        	Specimen_source_site_descrip varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        	Order_test_date datetime NULL,
        	Testing_lab_county varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        	Device_instance_ID_1 varchar(199) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        	Device_instance_ID_2 varchar(199) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        	Device_type_ID_1 varchar(199) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
        	Device_type_ID_2 varchar(199) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
    ) ON [PRIMARY]
END