name: Build and push reporting-pipeline-service image to ECR
on:
  push:
    branches:
      - main
      - rel-**
    #      Uncomment the following line only to test the build and deploy from private branches.
    #      - CNDIT-*
    #      - CNDE-*
    paths:
      - "reporting-pipeline-service/**"
      - "build.gradle"
      - "settings.gradle"
      - "gradle/**"
      - ".github/workflows/Build-and-deploy-reporting-services.yaml"

jobs:
  call-build-reporting-pipeline-service-container-workflow:
    permissions:
      id-token: write
      contents: read
      security-events: write
    name: Build Reporting Pipeline Service Container
    uses: CDCgov/NEDSS-Workflows/.github/workflows/Build-gradle-microservice-container.yaml@main
    with:
      microservice_name: nbs7-reporting-pipeline
      dockerfile_relative_path: -f ./reporting-pipeline-service/Dockerfile .
      environment_classifier: SNAPSHOT
      java_version: "21"
    secrets:
      NBS_ACCOUNTID: ${{secrets.NBS_ACCOUNTID}}
